### ISSUE TITLE
'PyInstaller.hooks.hook-PIL' not found while handling absolute import

### ISSUE THREAD

**Issue by aodock** [pyinstaller/pyinstaller#1395]
I found that this is just an empty file being missing on the `Pyinstaller/hooks`. I have tried installing `Pyinstaller` from source and through `pip`. In both ways i have to create that file manually,..
Is this a bug ,..?

**Comment by matysek** [comment]
Thanks for reporting. Python might complain that the parent hook module is missing (hook-PIL) but child module hooks are still there (hook-PIL.imaging). This kind of message is known. If it otherwise works for you then it is no bug.

In the development version it was fixed that empty parent hook modules are not necessary.

**Comment by aodock** [comment]
thanks

**Comment by aodock** [comment]
thanks

**Comment by aodock** [comment]
HI,.. I tried installing the newest version,.. I still get that same error,..
so i also tried `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` .. no change

**Comment by htgoebel** [comment]
> I still get that same error

Is this an error and PyInstaller fails freeing your program? Please post the *exact* error message. We need more infos, please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
