### ISSUE TITLE
R6034 error only on single-file executable (Win7 64 bit and Python 2.7.10)

### ISSUE THREAD

**Issue by giumas** [pyinstaller/pyinstaller#1516]
On Win7 64bit and Python 2.7.10 32bit, I have a quite large GUI application (using `wxPython`) that it works properly when frozen as single-folder, but fails with R6034 error when frozen as single-file.

Using `Process Explorer`, I noticed that only in single-file mode, the process loads 2 instances of `mscvr90.dll` and `msvcp90.dll`. 

![r6034_issue_msvcr390](https://cloud.githubusercontent.com/assets/2849257/10051160/1d04280c-61ee-11e5-90f2-285b14c265e8.PNG)

The single-folder application instead load just 1 instance of the 2 dlls, but not from the local folder:

![r6034_issue_working_singlefolder](https://cloud.githubusercontent.com/assets/2849257/10051306/f420b134-61ee-11e5-937a-713bbbabd2b1.PNG)

If I use the same environment with a `PySide` application I don't get errors.

I have looked at the past tickets on the topic as well as on StackOverflow, but I am still struggling to debug the issue:

* https://github.com/pyinstaller/pyinstaller/issues/522 : I am not renaming the executable
* https://github.com/pyinstaller/pyinstaller/issues/314 : I got the same error both on official CPython and Miniconda
* https://github.com/pyinstaller/pyinstaller/issues/689 : I am not using Portable Python
* http://stackoverflow.com/questions/17468135/pyinstaller-and-r6034-error : It does not work in my case
* http://stackoverflow.com/questions/11833301/python-executable-getting-a-runtime-error-r6034 : No useful information from Dependency Walker, since the warnings are the same as the single-folder mode.

What do you suggest?

**Comment by codewarrior0** [comment]
Read [How To Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). What version of PyInstaller did you use? Try the latest `python3` branch - it supports Python 2.7 too.

**Comment by giumas** [comment]
![pyinstaller_version](https://cloud.githubusercontent.com/assets/2849257/10051733/feffea14-61f0-11e5-91c4-7ec304aba0c5.PNG)

**Comment by codewarrior0** [comment]
That is not a released version. `git rev-parse head` will give you the commit ID. Again, try the latest `python3` branch.

**Comment by giumas** [comment]
The commit ID is the latest: acffffab6384f45a01a1c3e35551b3bca67d10d2

**Comment by codewarrior0** [comment]
Do you have an associated Python stack trace? Can you come up with a minimal `wxPython` program that reproduces the error?

**Comment by codewarrior0** [comment]
What version of `wxPython` are you using?

**Comment by giumas** [comment]
After the error message:

![r6034](https://cloud.githubusercontent.com/assets/2849257/10052518/79f829b2-61f5-11e5-9998-8eddd45d097d.PNG)

I get this stack trace:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xxxxxxx\appdata\local\yyyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "c:\hhhhhhh\ssss\zzzzzzz\ppp\oldgui\ppp_gui.py", line 3, in <module>
        import wx
      File "c:\users\xxxxxxx\appdata\local\yyyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxxxxx\AppData\Local\yyyyyy\py2\lib\site-packages\wx-3.0-msw\wx\__init__.py", line 45, in <module>
        from wx._core import *
      File "c:\users\xxxxxxx\appdata\local\yyyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxxxxx\AppData\Local\yyyyyy\py2\lib\site-packages\wx-3.0-msw\wx\_core.py", line 4, in <module>
        import _core_
      File "c:\users\xxxxxxx\appdata\local\yyyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 467, in load_module
        module = imp.load_module(fullname, fp, filename, ext_tuple)
    ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

So the issue seems to be related to `wxPython` (but it works on single-folder mode):
`wx.__version__`: `3.0.0.0`

**Comment by giumas** [comment]
I will work later on the minimal example.

I don't know if it is related, but the single-folder application crashes at exit with this error message:

![single_folder_error_message](https://cloud.githubusercontent.com/assets/2849257/10052779/95312eee-61f6-11e5-81e1-c5ed37797386.PNG)

without any stack trace.

**Comment by giumas** [comment]
Here the minimal example grabbed directly from http://wiki.wxpython.org/GettingStarted:

    import wx
    import random
    
    def GetRandColor():
        red = random.randint(0,255)
        green = random.randint(0,255)
        blue = random.randint(0,255)
        return (red, green, blue)
    
    class ColorPanel(wx.Panel):
        def __init__(self, parent, color='rand'):
            wx.Panel.__init__(self, parent)
            if color == 'rand':
                color = GetRandColor()
                self.Bind(wx.EVT_MOTION, self.OnMouseMove)
            self.SetBackgroundColour(color)
    
        def OnMouseMove(self, evt):
            self.SetBackgroundColour(GetRandColor())
            self.Refresh()
            evt.Skip()
    
    class MyFrame(wx.Frame):
        def __init__(self):
            wx.Frame.__init__(self, None, title="Hello Sizers")
            vSizer =wx.BoxSizer(wx.VERTICAL)
            hSizer = wx.BoxSizer(wx.HORIZONTAL)
            red = ColorPanel(self, 'red')
            blue = ColorPanel(self, 'blue')
            green = ColorPanel(self, 'green')
            rand = ColorPanel(self)
    
            red.SetSize((100, 100))
            rand.SetSize((100, 100))
            green.SetSize((-1, 100))
            blue.SetSize((-1, 100))
    
            vSizer.Add(rand, 0, wx.EXPAND)
            vSizer.Add(green, 1, wx.EXPAND)
            vSizer.Add(blue, 2, wx.EXPAND)
    
            hSizer.Add(red, 0, wx.EXPAND)
            hSizer.Add(vSizer, 1, wx.EXPAND)
    
            self.SetSizer(hSizer)
            self.Fit()
    
            self.Show()
            self.Bind(wx.EVT_CLOSE, self.OnClose)
    
        def OnClose(self, evt):
            dlg = wx.MessageDialog(self, 'Are you sure you want to close My World?',
                            'Closing...', wx.YES_NO | wx.ICON_QUESTION)
            ret = dlg.ShowModal()
            dlg.Destroy()
    
            if ret == wx.ID_YES:
                evt.Skip()
    
    app = wx.App(0)
    MyFrame()
    app.MainLoop()

The single-file mode **works** for me out-of-the-box using `PyInstaller 2.1`, but **fails** both with `3.0.dev2` (using `pip install --pre pyinstaller`) and with the latest `python3` commit (`acffffab6384f45a01a1c3e35551b3bca67d10d2`).

Same R6034 error. And here is the stack trace:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xxxxx\appdata\local\yyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6+acffffa-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxxx\AppData\Local\yyyyy\py2\lib\site-packages\wx-3.0-msw\wx\__init__.py", line 45, in <module>
        from wx._core import *
      File "c:\users\xxxxx\appdata\local\yyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6+acffffa-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxxx\AppData\Local\yyyyy\py2\lib\site-packages\wx-3.0-msw\wx\_core.py", line 4, in <module>
        import _core_
      File "c:\users\xxxxx\appdata\local\yyyyy\py2\lib\site-packages\PyInstaller-3.0.dev6+acffffa-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 467, in load_module
        module = imp.load_module(fullname, fp, filename, ext_tuple)
    ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
    minimal returned -1

**Comment by matysek** [comment]
Could this be related to #1367 ?

**Comment by codewarrior0** [comment]
It is more closely related to #1180 

Error R6034 is "Attempted to load CRT without activation context present".

This is what I think is happening:

Onefile and onedir builds handle activation contexts differently. In onedir builds, the initial (Process Default) context is loaded automatically by Windows from the "appname.exe.manifest" file alongside the app. This context provides linkage info for locating the CRT DLLs. However, in onefile builds, the initial context does not contain this linkage info. Because the CRT DLLs are going to be in a temporary folder, a second context is created at runtime after the temp folder is extracted, and this second context is *not* the Process Default context.

`wxPython` also creates its own activation context while loading its core DLLs, with the aim of using modern visual styles by loading the newer version of the Common Controls library. In onefile mode, where the Process Default context does not link to the CRT, this activation context temporarily overrides our own secondary context, which means when the CRT is loaded, it isn't loaded as an assembly (thus the second pair of CRT DLLs in your Process Monitor). The CRT itself inspects the context to see if it was loaded as an assembly; and because it isn't, it throws up error R6034 and dies.

Observing that everything works on PyInstaller 2.1 supports this: In 2.1, both onefile and onedir have a Process Default context that links to the CRT. This is a bug: onefile builds can't have an embedded manifest that links the CRT per #1180, and fixing that bug is what introduced the R6034 error. 

What can be done now is to change the `CreateActCtx` call to pass a flag that says "This explicitly loaded context should become the Process Default" context - but to use this, onefile builds can't have an embedded manifest at all, or else that manifest becomes the Process Default and calling `CreateActCtx` with that flag will fail. I'm going to try this and see if I still get the R6034 error.

**Comment by giumas** [comment]
>   I'm going to try this and see if I still get the R6034 error.

Based on this last sentence, I assume that you have been able to reproduce my error.

**Comment by codewarrior0** [comment]
>  I assume that you have been able to reproduce my error.

All it took was `import wx`.

I found what the crash-on-exit is too. It's an "early deactivation" error - apparently wx doesn't clean up after itself by deactivating the context it created. There's an extra flag I can pass to `DeactivateActCtx` for that, too.

**Comment by matysek** [comment]
@codewarrior0 is this something that should be fixed for 3.0?

**Comment by codewarrior0** [comment]
It may as well go into 3.0, since it already has a full overhaul of how assembly manifests are handled, compared to 2.1. I've got my changes done and I'm about to push so @giumas can try them.

**Comment by codewarrior0** [comment]
@giumas Try the latest `python3` branch. This should be fixed as of 2cec73aa996e232649ea5a760647dd972bbea14b

**Comment by giumas** [comment]
Using https://github.com/codewarrior0/pyinstaller 2cec73aa996e232649ea5a760647dd972bbea14b, everything works smoothly on my machine (both the minimal example and my original application). This commit also fixed the crash at exit.

Thank you for being so responsive to my issue!

**Comment by codewarrior0** [comment]
No problem. Thanks for testing.

Watch out for #1367, though. It still isn't fixed.

**Comment by mba7** [comment]
I had the same issue with pyinstaller 3.2 and python 2.7.11.

Getting back to pyinstaller 3.1 resolved the problem :)

**Comment by hubumi** [comment]
pyinstaller 3.1 : ImportError: The 'six' package is required...
pyinstaller 3.2 : Same issue
pyinstaller 3.1.1 : Resolved the problem :+1:

**Comment by philipgoh** [comment]
Ditto. Going back to pyinstaller 3.1.1 solved the problem. On 3.2 I was getting "R6034 error".

**Comment by stephenrauch** [comment]
@mba7, @hubumi , @philipgoh 

This bug was closed 8/9 months ago.  R6034 is a cry for help from windows at a fairly low level, and thus can have plenty of causes. R6034 was also reported in #1985. Can one, or all of you, check to see if the tip of the develop branch resolves your issue?  And then, if #1985 looks like a similar issue, report your testing results there.  And if #1985 does not look familiar, you could open a new bug.

**Comment by philipgoh** [comment]
This looks like #1985. Installing the latest development build removes fixes it.

**Comment by harry159821** [comment]
thanks you people, i got this error when i make a exe with import lxml , pyinstaller 3.1.1 solved this problem
