### ISSUE TITLE
Importing zipped eggs broken (migrate egg tests to pytest)

### ISSUE THREAD

**Issue by gkorf** [pyinstaller/pyinstaller#1581]
* When building my project with pyinstaller 3.0, modules are reported missing for dependencies which are found as zipped eggs.
* If I unzip the egg, the module is imported properly.
* Tested on Linux, Python 2.7.6 and virtualenv.
* I think this behavior is introduced in https://github.com/pyinstaller/pyinstaller/commit/0a5075f096d79e5a8bc97d5fcec5c6a75fe1a83e
* it happens with both: Python 2 and 3
* When trying module `ws4py` from the example in a comment then there are these warnings in warn.txt:
```
missing module named ws4py.websocket - imported by ws4py, /pyinstaller/develop/hello_test.py
missing module named ws4py - imported by /pyinstaller/develop/hello_test.py
```
* It looks like modulegraph is not able to find modules from zipped eggs so there is a regression in PyInstaller 3.0.

**Comment by matysek** [comment]
@gkorf Do you have any code example to reproduce this issue?

**Comment by gkorf** [comment]
In a virtualenv run:
$ pip install pyinstaller
$ pip install --egg ws4py

$ cat main.py
from ws4py import websocket
if __name__ == "__main__":
    print websocket

$ pyinstaller main.py
$ ./dist/main/main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ws4py
main returned -1

**Comment by matysek** [comment]
@gkorf Thanks for the example.

**Comment by matysek** [comment]
It looks like modulegraph has lost the ability to detect `.eggs` and in this case the module `ws4py` is recognized as a `missing` module and written to `warnings.txt`.

**Comment by htgoebel** [comment]
Setting to medium as there is a simple work-around: Just do not install as `.egg`.

**Comment by matysek** [comment]
Well, I found out that on my Linux fc22 `setuptools` is in virtualenv installed as an .egg and thus all modules that require `pkg_resources` fail because modulegraph cannot find it. Not sure what workaround is for this.

**Comment by htgoebel** [comment]
Okay, re-prioritizing to high.

**Comment by gkorf** [comment]
Also, running setup.py install (using setuptools) on a project, it will
install the zip-safe dependencies as eggs.

**Comment by matysek** [comment]
@htgoebel I migrated the `test_eggs` to pytest and marked them as xfail. `egg4testing` directory is in `./tests/scripts`.

**Comment by matysek** [comment]
While working  on this it looks like bundling datas of zipped .egg files never worked on Windows.

**Comment by htgoebel** [comment]
Only on WIndows?

**Comment by matysek** [comment]
@htgoebel Where are put data files for zipped eggs? Should they be kept unpacked? e.g. `MEIPASS/zipped_egg/data/datafile.tx`?

**Comment by matysek** [comment]
I see, they are bundled as modules:
```
 'xml.sax.saxutils': (0, 222411, 5039),
 'xml.sax.xmlreader': (0, 310728, 5448),
 'xmlrpc': (1, 1342618, 90),
 'xmlrpc.client': (0, 1328976, 13642),
 'zipfile': (0, 798329, 20182),
 'zipped_egg': (1, 1201244, 227),
 'zipped_egg/data/datafile.txt': (2, 1492007, 38)}
? 
```

**Comment by matysek** [comment]
This should be fixed. @gkorf or @JokerQyou could anyone of you test this?

**Comment by codewarrior0** [comment]
Huh. I think I ran into this bug, investigated it, fixed it, and somehow lost the commit a few days ago. It happened when loading `argparse` from an egg.

The problem I had was that `argparse.py` would be a `InvalidCompiledModule`. I found out the PEP 302 loader for eggfiles would return ".pyc" as the filetype for the module, but `ModuleGraph._find_module_path` would always call `get_source` on the loader and return the source code along with the ".pyc" filetype. Later, `_load_module` would try to interpret the source code as bytecode, fail, and mark the module as an `InvalidCompiledModule`.

This should be fixed in a6f4ba484f21b31620215f32451293c6964699ac.

**Comment by htgoebel** [comment]
I can confirm that the example from https://github.com/pyinstaller/pyinstaller/issues/1581#issuecomment-145651803 
- fails in a6f4ba4^
- passes in a6f4ba4
- passes in current head.

The example still fails due to module `socket` missing - which is esp. curious since the string "socket" does not even occur in the warnings-file.

**Comment by htgoebel** [comment]
This should be solved now, too. see 707b0191c4a8ca76c7a80b4c65fc5efb664f03d4

(CI tests fail at the moment due to an different error.)

**Comment by benoit-pierre** [comment]
The behavior is still different than with 2.1: instead of including the egg in the `eggs` directory, the content is included, which is problematic when said egg is using `pkg_resources`.

**Comment by benoit-pierre** [comment]
Also, running pyinstaller a second time without '--clean' errors out, apparently when it tries to unpack the egg a second time:

```
WindowsError: [Error 183] File already exists: '/home/bpierre/progs/src/plover/build\\Plover\\plover-2.5.8-py2.7.egg'
Traceback (most recent call last):
  File "./windows/build.py", line 55, in <module>
    subprocess.check_call(cmd, cwd=builddir)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by matysek** [comment]
@benoit-pierre  pkg_resources is not yet implemented. Please either comment in #183 or report a new issue.

**Comment by benoit-pierre** [comment]
@matysek: it was supported in 2.1 when a package was included as an egg, as still mentioned in the FAQ:

> What about pkg_resources?
pkg_resources is currently not supported by PyInstaller. This means that an application using a library which uses the the pkg_resources API will probably not work out of the box. The only situation in which it works is when it's being used on .egg files (see above).

**Comment by benoit-pierre** [comment]
But with 3.0, the egg is not bundled as-is.
