### ISSUE TITLE
bootloader: exe location discovery in PATH broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#1634]
For binaries made with single-file mode, there is some code to find the actual position of the executable while traversing PATH, but it is incomplete and does not work as it is.

See my comments there:
https://github.com/pyinstaller/pyinstaller/commit/d2e749f0d1fede80828c29837940a9269f596ebb

This affects all systems where the special hacks (like looking into /proc) do not apply. It also bites if /proc is not mounted.

**Comment by ThomasWaldmann** [comment]
I try fixing this...

**Comment by ThomasWaldmann** [comment]
Needs a windows developer now to fix it on windows also.

**Comment by codewarrior0** [comment]
Should be fixed in 04d882111564a09d0bac0c9618f21fac5dd29caf

**Comment by ThomasWaldmann** [comment]
@codewarrior0 it worked for me on freebsd. the part that needed fixing was windows.

**Comment by ThomasWaldmann** [comment]
Please reopen, this is currently broken on freebsd, using code from develop branch:
```
$ sudo umount /proc
$ borg.exe
Cannot open self /vagrant/borg/borg/borg.exe or archive /vagrant/borg/borg/borg.exe.pkg
$ sudo mount -t procfs none /proc
$ borg.exe
usage: borg.exe [-h] [-V]
...
```                
You see, without /proc mounted, it does not work. It finds the exe and executes it, but then the exe does not find its location via PATH. Only case it finds itself is when the exe is in cwd.

With /proc mounted it does. So /proc-based discovery of the exe locations works.

**Comment by dzimbeck** [comment]
This is not fixed, having the problem with newest build of pyinstaller. Its causing weird installer bugs and complete failure on WineBottler in mac. "Cannot open self"

**Comment by ThomasWaldmann** [comment]
@dzimbeck need more details. pyinstaller version, how to reproduce (best would be some simple commands without "winebottler"), mac os x version?

**Comment by dzimbeck** [comment]
3.11... built some complex crypto software and Pyqt4. Python 2.78
Same bug as here: https://github.com/pyinstaller/pyinstaller/issues/1165

Spec file is standard, running pyinstaller --onefile

Ive been at this for 20 hours straight looked at every thread for ways to solve it. Nothing works.

I've tried 2.1 pyinstaller.

HERE IS THE CRAZY PART:
I built the source with the identical settings and code, only a different name and different icon. (so ran it on Source1.py which was identical to Source2.py)

Source1.py runs perfect

Source2.py crashes no matter what.

Is it possible something is being stripped at the end and destroying the bootloader?

**Comment by ThomasWaldmann** [comment]
can you provide a simple script / source file that reproduces the problem?

**Comment by dzimbeck** [comment]
Hmm, so I tested a theory that winebottler was causing the issue, and it turns out this was the case. So wine might cause conflicts with these builds. I unfortunately, don't have a small source. If you want i can post the source but it takes a while to build it completely for distro.

I've now built this from a different Mac VM and it works now. :)

**Comment by patrickkidd** [comment]
I _think_ this is the right issue to post this, but I am getting the "Cannot open self" error when trying to call os.execl to restart the application after auto-updating the app bundle. Cheers
