### ISSUE TITLE
Appveyor failures

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#2024]
Appveyor is broken is several weird ways, which makes it hard to tell if new pull requests actually work or not.

From https://ci.appveyor.com/project/matysek/pyinstaller/build/1037, I see the following failures:

# Python 3.5
Starting at https://ci.appveyor.com/project/matysek/pyinstaller/build/1037/job/17rboj92io1xrli1#L1954:
```
FAIL tests/functional/test_basic.py::test_pywin32_win32ui[onedir] 
FAIL tests/functional/test_basic.py::test_pywin32_win32ui[onefile]
```

There's no error or failure message in the logs. ???

# Python 3.4
Starting at https://ci.appveyor.com/project/matysek/pyinstaller/build/1037/job/labch67uk3td15yn#L1793:
```
FAIL tests/functional/test_libraries.py::test_tkinter[onefile]
FAIL tests/functional/test_libraries.py::test_sphinx[onefile]
FAIL tests/functional/test_libraries.py::test_markdown[onefile]
```

# Python 3.3
These are the same as the Python 3.4 failures. Starting at https://ci.appveyor.com/project/matysek/pyinstaller/build/1037/job/y1iqih8x12oxfp4n#L1725:
```
FAIL tests/functional/test_libraries.py::test_tkinter[onefile]
FAIL tests/functional/test_libraries.py::test_sphinx[onefile]
FAIL tests/functional/test_libraries.py::test_pylint[onefile]
```

### test_tkinter
There are no exceptions or errors in the output from the run. ???

### test_sphinx
The runtimes for the Sphinx test is very high (see below). The [output](https://ci.appveyor.com/project/matysek/pyinstaller/build/1037/job/y1iqih8x12oxfp4n#L2048) from both seems like the binary never finished running; perhaps this was killed by the test framework? But other long-running tests passed.

Output:
```
---------------------------- Captured stderr call -----------------------------
PyInstaller Bootloader 3.x
LOADER: executable is c:\users\appveyor\appdata\local\temp\1\pytest-of-appveyor\pytest-0\popen-gw1\test_sphinx_onefile_0\dist\pyi_lib_sphinx.exe
LOADER: homepath is c:\users\appveyor\appdata\local\temp\1\pytest-of-appveyor\pytest-0\popen-gw1\test_sphinx_onefile_0\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is c:\users\appveyor\appdata\local\temp\1\pytest-of-appveyor\pytest-0\popen-gw1\test_sphinx_onefile_0\dist\pyi_lib_sphinx.exe
LOADER: Extracting binaries
------------------------------ Captured log call ------------------------------
configure.py                28 DEBUG    Testing for UPX ...
configure.py                53 INFO     UPX is not available.
__main__.py                 80 INFO     PyInstaller: 3.3.dev0+g8ce3016.mod
```

Run times:
```
========================== slowest 10 test durations ==========================
163.53s call     tests/functional/test_libraries.py::test_sphinx[onefile]
156.48s call     tests/functional/test_interactive.py::test_ipython[onedir]
109.51s call     tests/functional/test_interactive.py::test_ipython[onefile]
94.92s call     tests/functional/test_libraries.py::test_sphinx[onedir]
54.86s call     tests/functional/test_interactive.py::test_pyside[onefile]
49.94s call     tests/functional/test_libraries.py::test_pylint[onefile]
48.22s call     tests/functional/test_libraries.py::test_tkinter[onefile]
```

### test_pylint
Like the Sphinx failure, the output suggests that the process was killed. However, its run time is much shorter. ???

# Python 2.7
```
FAIL tests/functional/test_basic.py::test_module__file__attribute[onefile] 
FAIL tests/functional/test_basic.py::test_module_attributes[onedir] 
FAIL tests/functional/test_basic.py::test_module_attributes[onefile] 
FAIL tests/functional/test_basic.py::test_module_reload[onedir] 
FAIL tests/functional/test_basic.py::test_module_reload[onefile] 
```

## Analysis

All the errors above report:
```
E                   WindowsError: [Error 8] Not enough storage is available to process this command
 
c:\python27\lib\site-packages\pefile.py:1767: WindowsError 
```

Limited hard drive space on the Appveyor process? The output from py.test can reach GB of space. But why do these fail, instead of others?

**Comment by bjones1** [comment]
Even more fun, see different issues on my local Windows PC:

# Python 2.7

```
FAIL tests/functional/test_libraries.py::test_future[onedir]
FAIL tests/functional/test_libraries.py::test_future[onefile]
```

The root case:
```
Traceback (most recent call last):
  File "scripts\pyi_future.py", line 66, in <module>
  File "site-packages\future\types\newrange.py", line 122, in __getitem__
  File "site-packages\future\types\newrange.py", line 134, in __getitem_slice
OverflowError: cannot fit 'long' into an index-sized integer                      
```

The same errors occurs from the command line:
```
E:\pyinstaller>python tests\functional\scripts\pyi_future.py
Traceback (most recent call last):
  File "tests\functional\scripts\pyi_future.py", line 66, in <module>
    for i in range(10**15)[:10]:
  File "C:\Users\bjones\Downloads\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\future\types\newrange.py", line 122, in __getitem__
    return self.__getitem_slice(index)
  File "C:\Users\bjones\Downloads\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\future\types\newrange.py", line 134, in __getitem_slice
    scaled_indices = (self._step * n for n in slce.indices(self._len))
OverflowError: cannot fit 'long' into an index-sized integer
```

I'm using 32-bit Python, which is the likely cause. This is fixed in xxx.

**Comment by stephenrauch** [comment]
```
WindowsError: [Error 8] Not enough storage is available to process this command
c:\python27\lib\site-packages\pefile.py:1767: WindowsError 
```

Is a [memory leak in mmap](http://stackoverflow.com/questions/26047771/loadlibrary-fails-with-error-8-error-not-enough-memory).  We don't currently explicitly call close on the PE() object after finishing with it.  Probably not generally an issue, but if the test suite is not exiting the process it could accumulate a lot of memory.  Might also explain the seeming random nature of the failures.

**Comment by bjones1** [comment]
Thanks for the help! I look forward to seeing what Appveyor says when it (finally) finished building #2026...

**Comment by leycec** [comment]
@bjones1 Thanks for exhaustively enumerating the Appveyor carnage. You are the living legend. Long-lived test processes exhausting available resources seems like a plausible enough explanation for sporadic failures under Python 2.7.

What's up with Python 3.x, though? Why do tests locally succeed but remotely fail? Why doesn't Appveyor explicitly report anything? Why does `test_markdown` fail under Python 3.4 but **is not even listed under Python 3.3**? Why does leycec ask, "Why?" I am without wisdom in this matter.

`test_markdown` seems like low-hanging fruit here. How is it possible that the [Python 3.3 Appveyor run](https://ci.appveyor.com/project/matysek/pyinstaller/build/1037/job/y1iqih8x12oxfp4n#L1725) failed to even list `test_markdown` as an `XFAIL` or `SKIP`? Since only three tests failed _and_ since we pass `--maxfail 5` to `py.test` on Appveyor, this test should at least be listed. The `markdown` library _should_ be generally available for all Python versions and platforms, including Python 3.3 under Windows. Even if it isn't, however, the `@importorskip` decorator should have simply flagged this test as a `SKIP`.

`</sigh>`

**Comment by bjones1** [comment]
Updates:

# Python 2.7 on Appveyor
The failures after @stephenrauch's helpful fixes are now:
```
FAIL tests/functional/test_libraries.py::test_cherrypy[onefile]
FAIL tests/functional/test_libraries.py::test_sphinx[onefile]
FAIL tests/functional/test_libraries.py::test_pygments[onefile]
```
...which looks more like Python 3.3 and 3.4. Progress!

**Comment by bjones1** [comment]
@leycec. I'm still struggling to understand. One possibility: per #2011, I think much of the useful error info is not being shown. I'll experiment with that (invoke Appveyor's `py.test` with the `-s` option) as soon as I can find a minute. First, I'll try fixing the local failures, since those are easier to deal with.

I'm completely lost re: `test_markdown`. My first hope is to get everything passing, and hope that something magically fixes itself...

**Comment by leycec** [comment]
Could the failure to even list `test_markdown` under Python 3.3 be a subtle `xdist` parallelization issue? The output clearly shows the installation of the `markdown` dependency _and_ the collection (i.e., discovery) of the `test_markdown` test – but the test is never actually farmed out to an `xdist` slave for execution. Increasing `xdist` logging verbosity might yield a tasty nugget of truth, here.

@stephenrauch Thanks for the heroism.

**Comment by bjones1** [comment]
I'm trying just a few tests with better logging at https://ci.appveyor.com/project/bjones1/pyinstaller. Hopefully, something will turn up...

@leycec, interesting idea on `xdist`. I'll have to ponder when I'm more awake...

**Comment by leycec** [comment]
Godspeed and good sleep, stalwart Test Champion. :sleeping: 

It wouldn't surprise me if `xdist` is failing to behave reliably on Appveyor-hosted Windows containers, given the well-known fragility of the Win32 process model. When you're refreshed, a simpler solution to isolating the `test_markdown` issue might be to disable `xdist` altogether by temporarily removing the `-n 3` option passed to `py.test` from `appveyor.yml` and trying again. <sup>I am totally clueless, clearly.</sup>

**Comment by leycec** [comment]
Also, you imputed that:

> I'll experiment with that (invoke Appveyor's `py.test` with the `-s` option) as soon as I can find a minute.

Unfortunately, **`py.test` silently ignores the `-s` option when the `-n` option is passed.** Yes, it is unquestionably awful. This is a [long-standing `xdist` issue](https://github.com/pytest-dev/pytest/issues/680), purported to be resolved in the next major `xdist` release. (I wouldn't hold my fetid breath.)

Again, my recommendation remains the disable: **temporarily disable `xdist`.** It's only muddying the already polluted waters here.

**Comment by bjones1** [comment]
I've looked at the logs of the run linked above. My thoughts:

1. `xdist` was disabled -- I didn't pass the `-n` option.
2. The tests (mostly) passed, implying `xdist` or something else is producing some failures and silently ignoring some tests.
3. The first test, for cherrypy, was [strange](https://ci.appveyor.com/project/bjones1/pyinstaller/build/1.0.22/job/syrbc8xsofx33kcn#L987). It seems to silently abend or something -- the tests quits mid-line and moves to the next test to be execute. Appveyor doesn't even report the next line of its `.yml` file it's executing. Perhaps cherrypy is confusing the other tests, especially with `xdist`?
4. There's some [noise](https://ci.appveyor.com/project/bjones1/pyinstaller/build/1.0.22/job/syrbc8xsofx33kcn#L1006) about `PyQt5` during the collection phase for all tests I didn't expect. This would be worth a bit of checking.
5. `pylint` reports a [couple of warnings](https://ci.appveyor.com/project/bjones1/pyinstaller/build/1.0.22/job/syrbc8xsofx33kcn#L1438) -- this bears a bit of investigation. A hook file might need tuning.
6. `pip` complains that it's an old version. Would upgrading it make any difference?

For my next run, I'll try disabling `xdist` but running the full suite. I'm not sure if it will complete, though.

**Comment by bjones1** [comment]
I can reproduce `xdist` failures on my local PC (on Python 3.5 with 3de588aa4dd6dcbee1f03acb5f81b9edb5b38ab7). Unfortunately, the tests won't complete within the 1 hour Appveyor allots without `xdist`. Here's part of the error message produced:

```
INTERNALERROR>   File "C:\Users\bjones\Downloads\Anaconda3\lib\site-packages\execnet\gateway_base.py", line 984, in _send
INTERNALERROR>     message.to_io(self._io)
INTERNALERROR>   File "C:\Users\bjones\Downloads\Anaconda3\lib\site-packages\execnet\gateway_base.py", line 430, in to_io
INTERNALERROR>     io.write(header+self.data)
INTERNALERROR>   File "C:\Users\bjones\Downloads\Anaconda3\lib\site-packages\execnet\gateway_base.py", line 396, in write
INTERNALERROR>     self._write(data)
INTERNALERROR> OSError: [Errno 22] Invalid argument
INTERNALERROR>
```

**Comment by bjones1** [comment]
The magic command line to get a quick failure: `py.test -n auto --maxfail 1 -k test_ctypes_gen`. I don't have a C compiler (for Python 3.5) installed. I suspect this failure will go away when it's installed.

**Comment by bjones1** [comment]
I've submitted an issue that may or may not be related at https://github.com/pytest-dev/pytest-xdist/issues/65.

**Comment by leycec** [comment]
I friggin' _knew_ it was `xdist`. I really appreciate the blood, sweat, and bitter tears you've invested into this. The suspicious `OSError` raised by `execnet` is indicative of Win32 process hell. An obscenity on the face of humanity!

On a local (sadly, proprietary) scientific project I contribute to, `xdist` has been a nightmare of cross-platform quandries, insufficient configurability, and silent failure. We've had to forcibly rip it out of our testing stack altogether and pursue less... savoury means of optimizing tests. <sup>Thank _you,_ `cProfile`.</sup>

Clearly, permanently ripping `xdist` out of PyInstaller tests isn't a valid option. I _nearly_ have a Windows guest up and running. When I do, I'll relentlessly stab this issue until it keels over and coughs up working parallelized Windows tests. Thanks again, man!

**Comment by bjones1** [comment]
@leycec, thanks for the encouragement! I'd glad you're bringing Windows up. I'd really like to see #1991 be finished and merged...that's such a great contribution.

(And, I'd like to see Appveyor working again. One can only hope...)

**Comment by bjones1** [comment]
I tried without the ``-maxfail`` option, but still see failures. Also, on my personal Appveyor account, I seem to get a slower machine, since the tests don't complete. Other than fixing local failures, I'm not sure how to get Appveyor working.

**Comment by springermac** [comment]
@bjones1 you may need to do a run without the tests to populate the cache. I've been working on a nightly cache run so the cache doesn't get stale.

**Comment by bjones1** [comment]
Ah, I see. I'll try that out. Thanks!

**Comment by bjones1** [comment]
For now, I'm focusing on local Python 3.5 failures. The current list after 8c1773197f0eba5a60df26fba628e99ebcf40cad fixed the ctypes errors:

```
FAIL tests/functional/test_basic.py::test_pywin32_win32ui[onedir]
FAIL tests/functional/test_basic.py::test_pywin32_win32ui[onefile]
FAIL tests/functional/test_interactive.py::test_ipython[onedir]
FAIL tests/functional/test_libraries.py::test_pandas_extension[onedir]
FAIL tests/functional/test_libraries.py::test_pandas_extension[onefile]
```

**Comment by bjones1** [comment]
Looking at the `pandas` failures, it looks like PyInstaller includes both PyQt4 and PyQt5, which causes problems:

```
LOADER: Running pyi_rth_qt5.py
Traceback (most recent call last):
  File "PyInstaller\loader\rthooks\pyi_rth_qt5.py", line 61, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "e:\pyinstaller1\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class
```

Even in Python, you can't import both:
```
>>> import PyQt5.QtCore
>>> import PyQt4.QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

I'll add an `excludedimports` to `hook-PyQt5.py`.

**Comment by leycec** [comment]
**Ugh.** I'm astonished – simply astonished – that we haven't already added that `excludedimports`. For safety, I'd probably extend that by adding **symmetric exclusions.** That is:

* In `hook-PyQt4.py`:

        excludedimports = ['PyQt5']


* In `hook-PyQt5.py`:

        excludedimports = ['PyQt4']

I am now the bearer of bad news. The current `excludedimports` implementation is [effectively non-deterministic](https://github.com/pyinstaller/pyinstaller/issues/1901). Sometimes it works. Sometimes it doesn't. Only the RNG God decides which you get on any given freeze.

I am now the bearer of good news! I have a [prospective solution](https://github.com/pyinstaller/pyinstaller/pull/1651#issuecomment-192550183) in less than ten lines of code. In wild-eyed theory, this solution _should_ sanitize our `excludedimports` support to behave both deterministically _and_ efficiently.

I am again the bearer of bad news. This solution depends on the aforementioned #1991 as a hard dependency. Without #1991, _any_ attempt to refactor `ModuleGraph` should be greeted with a healthy dose of heathen scepticism and the evil eye. :ghost: 

But... Windows tests need to work before accepting non-trivial pull requests – which _definitely_ includes #1991. <sup>Darn you to heck, circular logic!</sup>

_Annnnnyway._ Maybe `excludedimports` will work good enough to get at least `test_pandas_extension` reliably passing. Maybe.

**Comment by bjones1** [comment]
I've played with this, but am now stuck. My thought was to exclude PyQt4 if PyQt5 is installed. While the approach above (specifically, I tried `excludedimports = ['PyQt4']` in `hook-PyQt5.py` doesn't work. Per the [manual](http://pyinstaller.readthedocs.io/en/stable/hooks.html#hook-global-variables)'s entry on `excludedimports`, "If an excluded module is imported only by the hooked module or one of its sub-modules, the excluded name and its sub-modules will not be part of the bundle. (If an excluded name is explicitly imported in the source file or some other module, it will be kept.)" Since `PyQt4` is a module or sub-module of `PyQt5`, this has no effect.

So, I modified `hook-PyQt4.py`: if PyQt5 is installed, `excludedimports = ['PyQt4']`. This doesn't work, because `excludedimports` applies to imports of the current module, not the module itself. In addition, I need to modify all the `hook-PyQt4.*.py` hooks as well since `import PyQt4.QtCore` doesn't invoke `hook-PyQt4.py`.

What I really want to do is delete a leaf from the modulegraph after it's added. Is the possible while still preserving the graph invariant (thinking back to red-black trees?) Perhaps a pre-safe hook that deletes the node passed to it? Help is much needed....

**Comment by stephenrauch** [comment]
How about you break the test suite into A and B?  Put pyqt4 into A and pyqt5 into B. Then only one or the other is installed, which would solve the conflict.  Appveyor allows an environment variable to be part of the test matrix. Define ONLY_A_TESTS or ONLY_B_TESTS could run half of the tests. With a reasonably even split between A/B this might also help with the test timeouts for us with different/slower appveyor accounts.  Not sure if you can set a requirements file on an environment variable, but if so....

**Comment by bjones1** [comment]
Looking at the other Python 3.5 failures, `test_ipython` also fails because of the PyQt4/PyQt5 conflict. The failure in `test_pywin32_win32ui` is different: doing a bit playing, PyInstaller renames `.pyd` files on Python 3.5 when copying them: `win32ui.pyd` becomes `win32ui.cp35-win32.pyd` in the `dist/` directory. Renaming it back to `win32ui.pyd` makes the test pass.

So...@codewarrior0, any ideas? Why do the rename? If it's a generally good thing, is there any (easy) way to add something to the hook to avoid this particular rename? Thanks for any and all thoughts!

**Comment by bjones1** [comment]
@stephenrauch, thanks for the suggestion. In this case, it's a local failure -- my Windows PC has both installed. However, we need to update Appveyor to install PyQt5, to get better coverage.

In terms of splitting the tests across two Appveyor runs, I'm not quite sure how to do that, and still have both execute for each commit or pull request. I *think* Appveyor would try to prevent this, since it effectively allows more CPU time per test.

**Comment by codewarrior0** [comment]
> Why do the rename?

The cause is Python 3.5 providing `cp35-win32.pyd` as the filename extension for extension modules through `importlib.EXTENSION_SUFFIXES`. This is according to [PEP 3149](https://www.python.org/dev/peps/pep-3149/) which puts various info about the C-level ABI into the extension module's filename to allow extension modules that were compiled differently to coexist. Setuptools-built .pyd files will also have this kind of filename.

I'm guessing that our CExtension importer needs to be changed to honor these filenames, or else our COLLECT step (via `add_suffix_to_extensions`) should ignore the ABI-marked extension provided by the `imp`/`importlib` module and just use `.pyd`.

**Comment by bjones1** [comment]
Hmmm. I certainly prefer the idea of not changing extensions -- that would seem the cleanest fix to me. It seems like the extension has already been stripped, though. Is there any way to preserve the extensions?

**Comment by bjones1** [comment]
I suspect that the way `win32ui.pyd` is non-standard in some way, thought I'm not sure in which way it is. All other tests, and all other `cp35-win32.pyd` files work just fine on my PC; this is the only failing test.

**Comment by bjones1** [comment]
@codewarrior0, I've changed `add_suffix_to_extensions` in https://github.com/bjones1/pyinstaller/commit/ee61140c2b58e7f43e7e19990b2d5e44df8d0d86 to use the extension's existing file extension. Would you mind taking a quick look to make sure I'm not breaking something else? Travis passes and my local Windows tests work.

**Comment by codewarrior0** [comment]
I don't see any problems with that. Keeping the original extension is probably safer than changing it. The issues addressed by PEP 3149 filenames don't really apply to our frozen executables.

**Comment by codewarrior0** [comment]
I think the condition should be `if os.path.splitext(inm)[1] not in EXTENSION_SUFFIXES`.

I don't see any problem with keeping the original extension. The issues addressed by PEP 3149 don't really apply to our frozen executables.

**Comment by bjones1** [comment]
Great! Thanks for the quick check. Yes, you're right -- I'll update the `if` condition, test that, then push. Thanks again for pointing me in the right direction for this one!

**Comment by stephenrauch** [comment]
@bjones1 

So don't know that it will be useful, but to finish the explanation:

Every AppVeyor build consists of one or more 'jobs'.  Each jobs is from a test 'matrix'.  The matrix is constructed using various dimensions. Pyinstaller is currently only using the python version dimension.  But it is also possible to iterate over other dimensions. All of the resulting jobs would execute for any commit.

The hour limit is for each element of the matrix (each job).  So if only half of the tests ran when a particular environment variable was set, they would each get an hour to run. Plus you could exclude installing some things that conflict with others.

https://www.appveyor.com/docs/build-configuration#build-matrix

**Comment by bjones1** [comment]
@leycec, any thoughts about modulegraphing about? This is, if both PyQt4 and PyQt5 are present and an import to PyQt4 or any of its submodules is detected, can I:

- Replace its node with a MissingModule?
- Delete its node entirely?
- In a pre-safe hook, add an alias from PyQt4 to PyQt4YouCannotImportMe to prevent the import from working?

Any thoughts would be appreciated...

**Comment by bjones1** [comment]
@stephenrauch, good point -- I completely overlooked that possibility. I'm playing a bit more with xdist to attempt to get it working, but if I still fail to do so I can certainly take this approach!

**Comment by bjones1** [comment]
A quick question for Appveyor experts (@springermac? @stephenrauch?) out there: on Python 2.7, one line takes about 10 minutes to execute; the same line on all other Python versions runs quickly. From the logs:

```
[00:02:44] pip.download     INFO Saved c:\users\appveyor\appdata\roaming\.pip-accel\sources\python_dateutil-2.5.3-py2.py3-none-any.whl
[00:02:44] pip.req.req_set  INFO Collecting pandas (from -r tests\requirements-libraries.txt (line 27))
[00:02:45] pip.download     INFO Downloading pandas-0.18.1.tar.gz (7.3MB)
[00:02:48] pip.download     INFO Saved c:\users\appveyor\appdata\roaming\.pip-accel\sources\pandas-0.18.1.tar.gz
[00:12:19] pip.req.req_set  INFO Collecting matplotlib (from -r tests\requirements-libraries.txt (line 28))
[00:12:19] pip.download     INFO File was already downloaded C:\Users\appveyor\AppData\Roaming\.pip-accel\sources\matplotlib-1.5.1-cp27-none-win32.whl
[00:12:19] pip.req.req_set  INFO Collecting pyreadline (from -r tests/requirements-win.txt (line 2))
[00:12:19] pip.download     INFO File was already downloaded C:\Users\appveyor\AppData\Roaming\.pip-accel\sources\pyreadline-2.1.zip
```

Any idea why? Or ways to speed this up?

**Comment by leycec** [comment]
@bjones1 Sorry for the itinerant delay. Capitalism demands increasing chunks of precious non-renewable lifetime. How I loathe it. :anger: 

> However, the approach above (specifically, I tried `excludedimports = ['PyQt4']` in `hook-PyQt5.py` doesn't work. Per the manual's entry on `excludedimports`, "If an excluded module is imported only by the hooked module or one of its sub-modules, the excluded name and its sub-modules will not be part of the bundle. (If an excluded name is explicitly imported in the source file or some other module, it will be kept.)" Since PyQt4 is not a module or sub-module of PyQt5, this has no effect.

_Urrrrgh._ I'd entirely forgotten about that unforgettable implementation detail. You're right; `excludedimports` is entirely unsuited for your purpose.

Ideally, hooks would support a global `excludedmodules` attribute permitting the hooked module to globally declare that all attempts to import modules listed in `excludedmodules` should be ignored _after_ that hooked module is first imported by the current application. Of course, there _is_ no `excludedmodules`.

> This is, if both PyQt4 and PyQt5 are present and an import to PyQt4 or any of its submodules is detected, can I:
>
>    Replace its node with a MissingModule?

**_No._** Never do this. The structure of the graph is _not_ safely modifiable. Once a node is added to the graph, the type of that node is effectively set in stone. There may be and probably are unique edge cases in which the structure of the graph _is_ safely modifiable – but this isn't one of them.

>   Delete its node entirely?

**_No._** Never do this. This is effectively what the current `excludedimports` implementation valiantly attempts to do. And we know how well _that_ worked out. (It didn't.)

 >   In a pre-safe hook, add an alias from `PyQt4` to `PyQt4YouCannotImportMe` to prevent the import from working?

**Yes!** I like the cut of your jibe. The alias idea is, indeed, clever. A just-in-time `ModuleGraph`-based solution is, indeed, _always_ the correct approach.

Sadly, we currently lack an appropriate hook type. `pre_find_module_path` hooks are applied _much_ too early in module importation. Likewise, `pre_safe_import_module` hooks are applied _before_ a module is successfully imported.

Ideally, there would exist a `post_safe_import_module` hook type applied _after_ a module is successfully imported. After all, you absolutely don't want to exclude `PyQt5` unless and only unless `PyQt4` was successfully imported. Assuming `post_safe_import_module` hooks existed, this exclusion would _probably_ be reliably implementable by adding a placeholder `PyQt4` node on successfully importing `PyQt5` and a placeholder `PyQt5` node on successfully importing `PyQt4` as follows:

* In `PyInstaller/hooks/post_safe_import_module/hook-pyqt4.py`:

        def post_safe_import_module(api):
            api.add_runtime_package('PyQt5')

* In `PyInstaller/hooks/post_safe_import_module/hook-pyqt5.py`:

        def post_safe_import_module(api):
            api.add_runtime_package('PyQt4')

Elegance personified, right? Except that this assumes the existence of a new hitherto unimagined hook type and is completely untested.

Adding a new hook type is non-trivial, but obviously feasible. I'd love to state that it's mostly a matter of boilerplate, but... that's probably a blatant lie. Ordinarily, I'd be all over this with a new pull request. This is the sort of gritty, dystopian code buggering I know best. Sadly, capitalism.

Do you reckon you're up for a bit of deep API work in the bowels of the PyInstaller codebase? If so, I could (s)mother you through the laborious process. Else, panic.

**Comment by bjones1** [comment]
@leycec, thanks for the help! Aargh, while I'd like to learn ModuleGraph, other projects now need my attention. Let me postpone this for now, but ask for your help later (hopefully) when I can find some time...

**Comment by bjones1** [comment]
This is (mostly) done. Per the comments above, there's still problems when both PyQt4 and PyQt5 are installed. I'll postpone that for another day. Thanks for all the help!

**Comment by leycec** [comment]
**No worries!** And thanks a metric ton for attending to the most Cthulhu-like aspects of this issue. When I shudder at Microsoft Windows, Microsoft Windows shudders back at me.

As the resident `ModuleGraph` code archaeologist, I'll try to scrape together some free time and implement the post-safe graph import hooks [documented above](https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-225336896). <sup>In all likelihood, nothing well ever be done.</sup>

**Comment by bjones1** [comment]
@leycec, any help will be wonderful! But time is always so limited...
