### ISSUE TITLE
cannot open self x or archive x.pkg

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#2357]
See there, strange issues: https://github.com/borgbackup/borg/issues/2002

The borgbackup 1.0.x binaries are built with pyinstaller 3.1.1 (single-file mode).

**Comment by ThomasWaldmann** [comment]
I suspect it is #1812. Can we have a 3.2.1 soon?

**Comment by htgoebel** [comment]
@codewarrior0 While that bug report [IMO](https://github.com/borgbackup/borg/issues/2002#issuecomment-272499139) is about two issues, at least one of it is it really strange: 
While [`readlink`](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_path.c#L295) returns the correct path to the executable, it is corrupted when [trying](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_main.c) -> [to](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_archive.c#L471) -> [access](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_archive.c#L66) -> [the file](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_archive.c#L69).

See end of https://github.com/borgbackup/borg/issues/2002#issuecomment-270840880 and https://github.com/borgbackup/borg/issues/2002#issuecomment-272080249.

**Comment by codewarrior0** [comment]
That is really strange. I'm stumped.

`executable` and `archivefile` are both good because we see them in the "Cannot output self" error.

The second and third args to `pyi_arch_setup` are just `strcat`'ed together (into a different string) and passed to `fopen`, yet the first `fopen` call shows something weird being catted on while the second `fopen` call is okay. I guess we'll have to wait to see what the `--debug` output shows.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/2002#issuecomment-272992651 solved.

It is because 3.1.1 in the pyinstaller repo does not have the fixed and freshly compiled bootloader.

So, if 3.1.x is still getting maintenance updates, this should be included in there.

If not, this issue can be closed as it is fixed in 3.2.1.

**Comment by htgoebel** [comment]
Thanks for the report. We are not maintaining old versions of PyInstaller, so I'm closing this on.

**Comment by felixhao28** [comment]
I am seeing this issue again with PyInstaller 4.0. I packed a python program (with multiple files) with python 3.7.9 on Ubuntu 16.04 and copied the packed executable to Ubuntu 20.04. **The binary works fine if directly invoked from the command line.** However if it is called from another process as a subprocess (I use boost::process::child but this shouldn't matter), the "cannot open self x or archive x.pkg" message starts to show up.

There are two completely separate python programs and this issue occurred on both of them.

At last, I downgraded to PyInstaller 3.6 and it works again.

**Comment by BoboTiG** [comment]
Could you provide a complete minimal test? With the boost part to easily reproduce. It would greatly help having a look at the issue :)

**Comment by rokm** [comment]
Sounds like this could be duplicate of #5179. Can you see if branch from PR #5232 fixes the issue for you? (You'll need to rebuild bootloader).

**Comment by felixhao28** [comment]
@BoboTiG @rokm 
I managed to reproduce this issue with the minimal code:
https://github.com/felixhao28/pyinstaller-bug-repro

I found that if I change "tk" to "./tk" in [main.cpp:12](https://github.com/felixhao28/pyinstaller-bug-repro/blob/master/cpp/main.cpp#L12), it will work fine. But it works fine regardless with PyInstaller 3.6.

**Comment by BoboTiG** [comment]
@rokm what is what I thought too. @felixhao28 could you try the fix from @rokm?

**Comment by rokm** [comment]
> I found that if I change "tk" to "./tk" in main.cpp:12, it will work fine. But it works fine regardless with PyInstaller 3.6.

The example as-is is throwing exception because boost process cannot find the `tk` executable (this has nothing to do with pyinstaller; it would have errored out for any other binary):
```
(venv) [rok@alpha dist]$ ./tfnative 
terminate called after throwing an instance of 'boost::process::process_error'
  what():  execve failed: No such file or directory
```

Ensuring that `tk` is in `PATH` gets us a bit further, but it still errors out (I've rebuilt the frozen application with bootloader debug enabled):
```
(venv) [rok@alpha dist]$ PATH=$pwd ./tfnative 
[52909] PyInstaller Bootloader 3.x
[52909] LOADER: Searching $PATH failed for tk[52909] LOADER: executable is /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname
[52909] LOADER: homepath is /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist
[52909] LOADER: _MEIPASS2 is NULL
[52909] LOADER: archivename is /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname
[52909] LOADER: Cannot open archive: /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname
[52909] LOADER: archivename is /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname.pkg
[52909] LOADER: Cannot open archive: /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname.pkg
[52909] Cannot open self /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname or archive /home/rok/tmp/pyi-2357/pyinstaller-bug-repro/dist/appname.pkg
```
The above issue (`Cannot open self appname or appname.pkg`) is a bug #5257 and has been since fixed by #5258. You can try rebuilding and installing the bootloader from `develop` branch.

**Comment by rokm** [comment]
If rebuilding the bootloader from `develop` does not fix the issue for you, rebuilding it from #5232 should, as that also restores the old `readlink`-based resolution, so behavior should be the same as in old PyInstaller versions.

**Comment by felixhao28** [comment]
> ... is throwing exception because boost process cannot find the tk executable

Well, that's strange, I tested both on CentOS 7.3 and Ubuntu 16.04 with boost 1.71.0 and I didn't need the "./" for boost to find the binary.

> could you try the fix from #2357 (comment)?

Sure, I will let you know the results soon.

**Comment by Mistikan** [comment]
Hey. I have a similar problem, but the situation is completely different.
I collected under NAS QNAP TS-419U borg.
The assembly was done using https://git.feneas.org/borg-binary-builder/borg-binaries.
Unfortunately, that binary file did not start for me. on the NAS itself, old glibc. For this reason, I changed the links to the interpreter and rpath using the patchelf tool. This led me to a problem in the post already.
What I have tried:
- collect as a single file and directory.
- downgrade pyinstaller == 3.6
[/] # uname -a
Linux nas01 3.4.6 # 1 Tue Oct 6 11:24:42 CST 2020 armv5tel unknown
[/] # ldd --version
ldd (GNU libc) 2.5
What else can I do to get borg running on the TS-419U?

**Comment by felixhao28** [comment]
> could you try the fix from #2357 (comment)?
@BoboTiG No it does not fix this.

```bash
wget https://github.com/rokm/pyinstaller/archive/bootloader-process-name.zip
unzip bootloader-process-name.zip
cd bootloader-process-name
python3.7 -m pip install .
```

> has been since fixed by #5258. You can try rebuilding and installing the bootloader from develop branch.
@rokm No it does not fix this either.

```bash
wget https://github.com/pyinstaller/pyinstaller/archive/develop.zip
unzip develop.zip
cd develop
python3.7 -m pip install .
```

PyInstaller 3.6 still works, after `python3.7 -m pip install pyinstaller==3.6.0`.

**Comment by BoboTiG** [comment]
Could you post the whole build log + error when you built using the fix we proposed?

**Comment by felixhao28** [comment]
<details><summary>With `https://github.com/rokm/pyinstaller/archive/bootloader-process-name.zip`:</summary>

```
[user@bogon pyinstaller-bug-repro]$ python3.7 -m pip install ../pyinstaller-bootloader-process-name/
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/pyinstaller-bootloader-process-name
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (41.2.0)
Requirement already satisfied: altgraph in /home/user/.local/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (0.17)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in /home/user/.local/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (2020.10)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... done
  Created wheel for pyinstaller: filename=pyinstaller-4.1.dev0-py3-none-any.whl size=2783817 sha256=1f8afa6fa2c28acaa328a208665280208927908672f8eaed57516b329230f61f
  Stored in directory: /home/user/.cache/pip/wheels/39/03/50/70846e1eb55f4f287262bed2910f581230fe4df31f83c8a128
Successfully built pyinstaller
Installing collected packages: pyinstaller
  Attempting uninstall: pyinstaller
    Found existing installation: pyinstaller 4.1.dev0
    Uninstalling pyinstaller-4.1.dev0:
      Successfully uninstalled pyinstaller-4.1.dev0
  WARNING: The scripts pyi-archive_viewer, pyi-bindepend, pyi-grab_version, pyi-makespec, pyi-set_version and pyinstaller are installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pyinstaller-4.1.dev0
[user@bogon pyinstaller-bug-repro]$ ./build.sh 
36 INFO: PyInstaller: 4.1.dev0
36 INFO: Python: 3.7.7
36 INFO: Platform: Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core
37 INFO: wrote /home/user/pyinstaller-bug-repro/tk.spec
39 INFO: UPX is not available.
40 INFO: Extending PYTHONPATH with paths
['/home/user/pyinstaller-bug-repro', '/home/user/pyinstaller-bug-repro']
42 INFO: checking Analysis
51 INFO: checking PYZ
54 INFO: checking PKG
54 INFO: Building because /home/user/.local/lib/python3.7/site-packages/PyInstaller/loader/pyimod01_os_path.pyc changed
54 INFO: Building PKG (CArchive) PKG-00.pkg
6645 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
6651 INFO: Bootloader /home/user/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
6651 INFO: checking EXE
6653 INFO: Building because /home/user/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run changed
6653 INFO: Building EXE from EXE-00.toc
6672 INFO: Appending archive to ELF section in EXE /home/user/pyinstaller-bug-repro/dist/tk
6691 INFO: Building EXE from EXE-00.toc completed successfully.
mkdir: cannot create directory ‘build’: File exists
CMAKE_CXX_COMPILER_ID=GNU
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/pyinstaller-bug-repro/cpp/build
/home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -S/home/user/pyinstaller-bug-repro/cpp -B/home/user/pyinstaller-bug-repro/cpp/build --check-build-system CMakeFiles/Makefile.cmake 0
/home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -E cmake_progress_start /home/user/pyinstaller-bug-repro/cpp/build/CMakeFiles /home/user/pyinstaller-bug-repro/cpp/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/user/pyinstaller-bug-repro/cpp/build'
make  -f CMakeFiles/tfnative.dir/build.make CMakeFiles/tfnative.dir/depend
make[2]: Entering directory `/home/user/pyinstaller-bug-repro/cpp/build'
cd /home/user/pyinstaller-bug-repro/cpp/build && /home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /home/user/pyinstaller-bug-repro/cpp /home/user/pyinstaller-bug-repro/cpp /home/user/pyinstaller-bug-repro/cpp/build /home/user/pyinstaller-bug-repro/cpp/build /home/user/pyinstaller-bug-repro/cpp/build/CMakeFiles/tfnative.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/user/pyinstaller-bug-repro/cpp/build'
make  -f CMakeFiles/tfnative.dir/build.make CMakeFiles/tfnative.dir/build
make[2]: Entering directory `/home/user/pyinstaller-bug-repro/cpp/build'
make[2]: Nothing to be done for `CMakeFiles/tfnative.dir/build'.
make[2]: Leaving directory `/home/user/pyinstaller-bug-repro/cpp/build'
[100%] Built target tfnative
make[1]: Leaving directory `/home/user/pyinstaller-bug-repro/cpp/build'
/home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -E cmake_progress_start /home/user/pyinstaller-bug-repro/cpp/build/CMakeFiles 0
build done!
[user@bogon pyinstaller-bug-repro]$ ./run.sh 
[4414] Cannot open self /home/user/pyinstaller-bug-repro/dist/appname or archive /home/user/pyinstaller-bug-repro/dist/appname.pkg

[user@bogon pyinstaller-bug-repro]$ 
```

</details>

<details><summary>With `https://github.com/pyinstaller/pyinstaller/archive/develop.zip`:</summary>

```
[user@bogon pyinstaller-bug-repro]$ python3.7 -m pip install ../pyinstaller-develop
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/pyinstaller-develop
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in /home/user/.local/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (2020.10)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (41.2.0)
Requirement already satisfied: altgraph in /home/user/.local/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (0.17)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... done
  Created wheel for pyinstaller: filename=pyinstaller-4.1.dev0-py3-none-any.whl size=2782936 sha256=941760728d32522f23723ecdaf75e6c9b93aa75a7888d8a93c3086e993e523a0
  Stored in directory: /home/user/.cache/pip/wheels/2e/aa/55/adf0a276228f26f35bb52681464f9b53bd333b079d28050ebb
Successfully built pyinstaller
Installing collected packages: pyinstaller
  Attempting uninstall: pyinstaller
    Found existing installation: pyinstaller 4.1.dev0
    Uninstalling pyinstaller-4.1.dev0:
      Successfully uninstalled pyinstaller-4.1.dev0
  WARNING: The scripts pyi-archive_viewer, pyi-bindepend, pyi-grab_version, pyi-makespec, pyi-set_version and pyinstaller are installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pyinstaller-4.1.dev0
[user@bogon pyinstaller-bug-repro]$ ./build.sh 
36 INFO: PyInstaller: 4.1.dev0
36 INFO: Python: 3.7.7
36 INFO: Platform: Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core
36 INFO: wrote /home/user/pyinstaller-bug-repro/tk.spec
42 INFO: UPX is not available.
43 INFO: Extending PYTHONPATH with paths
['/home/user/pyinstaller-bug-repro', '/home/user/pyinstaller-bug-repro']
48 INFO: checking Analysis
56 INFO: checking PYZ
64 INFO: checking PKG
65 INFO: Building because /home/user/.local/lib/python3.7/site-packages/PyInstaller/loader/pyimod01_os_path.pyc changed
65 INFO: Building PKG (CArchive) PKG-00.pkg
6545 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
6564 INFO: Bootloader /home/user/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
6564 INFO: checking EXE
6570 INFO: Building because /home/user/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run changed
6570 INFO: Building EXE from EXE-00.toc
6572 INFO: Appending archive to ELF section in EXE /home/user/pyinstaller-bug-repro/dist/tk
6585 INFO: Building EXE from EXE-00.toc completed successfully.
mkdir: cannot create directory ‘build’: File exists
CMAKE_CXX_COMPILER_ID=GNU
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/pyinstaller-bug-repro/cpp/build
/home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -S/home/user/pyinstaller-bug-repro/cpp -B/home/user/pyinstaller-bug-repro/cpp/build --check-build-system CMakeFiles/Makefile.cmake 0
/home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -E cmake_progress_start /home/user/pyinstaller-bug-repro/cpp/build/CMakeFiles /home/user/pyinstaller-bug-repro/cpp/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/user/pyinstaller-bug-repro/cpp/build'
make  -f CMakeFiles/tfnative.dir/build.make CMakeFiles/tfnative.dir/depend
make[2]: Entering directory `/home/user/pyinstaller-bug-repro/cpp/build'
cd /home/user/pyinstaller-bug-repro/cpp/build && /home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /home/user/pyinstaller-bug-repro/cpp /home/user/pyinstaller-bug-repro/cpp /home/user/pyinstaller-bug-repro/cpp/build /home/user/pyinstaller-bug-repro/cpp/build /home/user/pyinstaller-bug-repro/cpp/build/CMakeFiles/tfnative.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/user/pyinstaller-bug-repro/cpp/build'
make  -f CMakeFiles/tfnative.dir/build.make CMakeFiles/tfnative.dir/build
make[2]: Entering directory `/home/user/pyinstaller-bug-repro/cpp/build'
make[2]: Nothing to be done for `CMakeFiles/tfnative.dir/build'.
make[2]: Leaving directory `/home/user/pyinstaller-bug-repro/cpp/build'
[100%] Built target tfnative
make[1]: Leaving directory `/home/user/pyinstaller-bug-repro/cpp/build'
/home/user/tfnative2/downloads/cmake-3.18.2-Linux-x86_64/bin/cmake -E cmake_progress_start /home/user/pyinstaller-bug-repro/cpp/build/CMakeFiles 0
build done!
[user@bogon pyinstaller-bug-repro]$ ./run.sh 
[4341] Cannot open self /home/user/pyinstaller-bug-repro/dist/appname or archive /home/user/pyinstaller-bug-repro/dist/appname.pkg

[user@bogon pyinstaller-bug-repro]$ 
```

</details>

**Comment by rokm** [comment]
> wget https://github.com/rokm/pyinstaller/archive/bootloader-process-name.zip
unzip bootloader-process-name.zip
cd bootloader-process-name
python3.7 -m pip install .

This installs the precompiled version of bootloader that is checked in the repository. This precompiled version does not include the changes. 

You need to [rebuild the bootloader](https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html) yourself. E.g.,
```
unzip bootloader-process-name.zip
cd pyinstaller-bootloader-process-name
cd bootloader
python3.7 waf configure all
cd ..
python3.7 -m pip install .
```

**Comment by felixhao28** [comment]
Cool, now I confirm both "develop branch" and "PR bootloader-process-name" fix this issue.

**Comment by BoboTiG** [comment]
Super news! Tha you for confirming @felixhao28.

**Comment by BoboTiG** [comment]
@felixhao28  can you close the PR if it is all good for you?

**Comment by felixhao28** [comment]
> can you close the PR if it is all good for you?

PR? Do you mean this issue? This issue was not reopened by me. I am not authorized to close it.
