### ISSUE TITLE
Python error on build when importing flask_script on Windows (no issue on macOS)

### ISSUE THREAD

**Issue by smurphy917** [pyinstaller/pyinstaller#2393]
Having an issue with Flask-Script only on Windows. I'm able to build and run with no issues on macOS. 

With a simple test module, `pyinst_test.py`:
```python
import flask_script

if __name__ == '__main__':
    print("hello")
```
running `>pyinstaller --debug pyinst_test.py` gives the following:
```sh
125 INFO: PyInstaller: 3.3.dev0+68ed214
125 INFO: Python: 3.5.3
125 INFO: Platform: Windows-8.1-6.3.9600-SP0
125 INFO: wrote C:\Users\MyUser\workspace\test_space\pyinst_test.spec
125 INFO: UPX is not available.
140 INFO: Extending PYTHONPATH with paths
['C:\\Users\\MyUser\\workspace\\test_space',
 'C:\\Users\\MyUser\\workspace\\test_space']
140 INFO: checking Analysis
140 INFO: Building Analysis because out00-Analysis.toc is non existent
140 INFO: Initializing module dependency graph...
140 INFO: Initializing module graph hooks...
140 INFO: Analyzing base_library.zip ...
3878 INFO: running Analysis out00-Analysis.toc
3878 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by c:\users\MyUser\appdata\local\programs\python\python35-32\pyth
on.exe
4394 INFO: Caching module hooks...
4409 INFO: Analyzing C:\Users\MyUser\workspace\test_space\pyinst_test.py
5160 INFO: Processing pre-find module path hook   distutils
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python35-32\Scripts\py
installer-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+68ed214', 'console_scripts', 'pyinst
aller')()
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\building\build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\depend\analysis.py", line 144, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1436, in run_script
    self._scan_code(m, co, co_ast)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_impo
rts
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_
hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_pa
ckage
    target_module_headname, target_package_name, source_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_
module
    module_name, file_handle, pathname, metadata)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2115, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2951, in _load_package

    self._load_module(fqname, fp, buf, stuff)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_impo
rts
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_
hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_pa
ckage
    target_module_headname, target_package_name, source_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_
module
    module_name, file_handle, pathname, metadata)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2115, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2951, in _load_package

    self._load_module(fqname, fp, buf, stuff)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_impo
rts
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_
hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_pa
ckage
    target_module_headname, target_package_name, source_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_
module
    module_name, file_handle, pathname, metadata)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2115, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2951, in _load_package

    self._load_module(fqname, fp, buf, stuff)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2592, in _scan_code
    self._process_imports(module)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2881, in _process_impo
rts
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_
hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1510, in import_hook
    target_module = self._load_tail(target_package, target_module_partname)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 1723, in _load_tail
    submodule = self._safe_import_module(head, mname, submodule)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_
module
    module_name, file_handle, pathname, metadata)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\PyInstaller\lib\modulegraph\modulegraph.py", line 2164, in _load_module
    co = compile(co_ast, pathname, 'exec', 0, True)
  File "c:\users\MyUser\appdata\local\programs\python\python35-32\lib\site-p
ackages\jinja2\asyncsupport.py", line 35
    yield event
    ^
SyntaxError: 'yield' inside async function
```
OS: Windows
Python: 3.5.3
PyInstaller: 3.2.1 & 3.3.dev0+68ed214
Flask-Script: 2.0.5

**Comment by xoviat** [comment]
This failure occurs because jinja2 has included syntax that is only supported on Python 3.6 in their Python 3.5 distribution. Although jinja2 does not load this syntax on Python 3.5, PyInstaller does and thus fails. This issue is fixed by #2341, which is not yet merged.

**Comment by smurphy917** [comment]
Thanks, that's helpful. I'll take a look at differences between mac and windows dists for jinja2 and then close this.

**Comment by smurphy917** [comment]
There's an open [issue](https://github.com/pallets/jinja/issues/662) on jinja2 to make the imports conditional in order to be friendly to bytecompilers that I think should resolve this, assuming the issue is able to be resolved. However, for now I think just doing this should fix it:

```python
a = Analysis(['pyinst_test.py'],
             #...
             excludes=['jinja2.asyncsupport','jinja2.asyncfilters'],
             #...)
```

I'll test tomorrow when I can get back to my win32 test rig, then close the issue. I'm still not 100% sure why it only fails on win32--is this because of the win32 interpreter somehow, or is it a difference in the bytecompiler included in PyInstaller for win32 vs darwin? My curiosity may drive me deeper down this rabbit hole than is really productive...

**Comment by xoviat** [comment]
It's not just win32. I've seen failures on linux as well.

**Comment by htgoebel** [comment]
Depending on how quickly jinja2 gets fixed, we could add a hook checking both the python version and the (broken) jina2 versions and exclude the file there. Hmm, well we would not even need to check the jinja2 version, if these modules are new.

**Comment by xoviat** [comment]
@htgoebel The fix for this in in the py36 pr. It's simply a try...except block that ignores files with a parsing error.

**Comment by smurphy917** [comment]
I've confirmed that manually excluding `jinja2.asyncsupport` and `jinja2.asyncfilters` in the spec file is a successful workaround on win32. I've tagged this issue for closure once #2341 is merged.

**Comment by bwoodsend** [comment]
We have a `try: except` guard for syntax errors now. This should no longer come up.
