### ISSUE TITLE
`pkg_resources.resource_stream()` fails in --onefile mode

### ISSUE THREAD

**Issue by mafrosis** [pyinstaller/pyinstaller#2699]
Consider the below application using `python-daemon` and `pytz`.

    import daemon
    import pytz
    import logging

    logger = logging.getLogger('test1')

    def entrypoint():
        with daemon.DaemonContext():
            logger.setLevel(logging.INFO)
            fh = logging.FileHandler('/tmp/pyinst/loggy.log')
            logger.addHandler(fh)

            try:
                tz = pytz.timezone('US/Pacific')
                logger.info(tz)
            except Exception as e:
                logger.error(e, exc_info=True)

    if __name__ == '__main__':
        entrypoint()

The file `loggy.log` correctly contains `US/Pacific` when built with `--onedir`:

    pyinstaller --noconfirm --clean --name test1 --onedir test.py

However if I build with `--onefile`, the following exception is found in the log:

    'US/Pacific'
    Traceback (most recent call last):
      File "test1.py", line 20, in entrypoint
      File "pytz/__init__.py", line 181, in timezone
    pytz.exceptions.UnknownTimeZoneError: 'US/Pacific'

It seems that `pytz` is unable to locate the packaged `zonefile` data when built into a single executable file. I'm not sure where to go next with regard to fixing this. Any ideas are welcome!

Thanks

EDIT: including full output of pyinstaller:

    pyinstaller --noconfirm --clean --name test1 --onedir test1.py
    160 INFO: PyInstaller: 3.3.dev0+ce364f741
    160 INFO: Python: 3.5.3
    166 INFO: Platform: Darwin-16.6.0-x86_64-i386-64bit
    167 INFO: wrote /private/tmp/pyinst/test1.spec
    171 INFO: UPX is not available.
    172 INFO: Removing temporary files and cleaning cache in /Users/mafro/Library/Application Support/pyinstaller
    180 INFO: Extending PYTHONPATH with paths
    ['/private/tmp/pyinst', '/private/tmp/pyinst']
    180 INFO: checking Analysis
    180 INFO: Building Analysis because out00-Analysis.toc is non existent
    180 INFO: Initializing module dependency graph...
    184 INFO: Initializing module graph hooks...
    186 INFO: Analyzing base_library.zip ...
    5906 INFO: running Analysis out00-Analysis.toc
    5922 INFO: Caching module hooks...
    5926 INFO: Analyzing /private/tmp/pyinst/test1.py
    6429 INFO: Processing pre-find module path hook   distutils
    7569 INFO: Loading module hooks...
    7569 INFO: Loading module hook "hook-xml.py"...
    7966 INFO: Loading module hook "hook-pytz.py"...
    7995 INFO: Loading module hook "hook-pkg_resources.py"...
    8762 INFO: Processing pre-safe import module hook   win32com
    8768 INFO: Loading module hook "hook-distutils.py"...
    8770 INFO: Loading module hook "hook-pydoc.py"...
    8771 INFO: Loading module hook "hook-sysconfig.py"...
    8773 INFO: Loading module hook "hook-encodings.py"...
    8869 INFO: Loading module hook "hook-lib2to3.py"...
    8905 INFO: Looking for ctypes DLLs
    8941 INFO: Analyzing run-time hooks ...
    8947 INFO: Including run-time hook 'pyi_rth_pkgres.py'
    8961 INFO: Looking for dynamic libraries
    9060 INFO: Looking for eggs
    9060 INFO: Using Python library /Users/mafro/.pyenv/versions/3.5.3/Python.framework/Versions/3.5/Python
    9064 INFO: Warnings written to /private/tmp/pyinst/build/test1/warntest1.txt
    9119 INFO: checking PYZ
    9119 INFO: Building PYZ because out00-PYZ.toc is non existent
    9119 INFO: Building PYZ (ZlibArchive) /private/tmp/pyinst/build/test1/out00-PYZ.pyz
    9680 INFO: Building PYZ (ZlibArchive) /private/tmp/pyinst/build/test1/out00-PYZ.pyz completed successfully.
    9693 INFO: checking PKG
    9693 INFO: Building PKG because out00-PKG.toc is non existent
    9693 INFO: Building PKG (CArchive) out00-PKG.pkg
    9704 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
    9705 INFO: Bootloader /private/tmp/pyinst/lib/python3.5/site-packages/PyInstaller/bootloader/Darwin-64bit/run
    9706 INFO: checking EXE
    9706 INFO: Building EXE because out00-EXE.toc is non existent
    9706 INFO: Building EXE from out00-EXE.toc
    9706 INFO: Appending archive to EXE /private/tmp/pyinst/build/test1/test1
    9708 INFO: Fixing EXE for code signing /private/tmp/pyinst/build/test1/test1
    9714 INFO: Building EXE from out00-EXE.toc completed successfully.
    9718 INFO: checking COLLECT
    9718 INFO: Building COLLECT because out00-COLLECT.toc is non existent
    9719 INFO: Building COLLECT out00-COLLECT.toc
    10803 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

**Comment by htgoebel** [comment]
Is this the **minimal** example? Does the code pass if no daemon and no logging are used? Which of these two trigger the error?

**Comment by htgoebel** [comment]
Issue is in cause be `pkg_resources.resource_stream()` not working, see https://github.com/stub42/pytz/blob/release_2017.2/src/pytz/__init__.py#L91

**Comment by htgoebel** [comment]
Looks like we no not have a test-case for `resource_stream()`, only for `resource_string()`

**Comment by mafrosis** [comment]
This is the minimal example. The logging is necessary to see the error when running inside the DaemonContext. The error does not occur when the DaemonContext is not used.

I would like to attempt to fix this, but I don't really know where to start. I'll have a poke around the code this afternoon - any pointers are welcome!

**Comment by htgoebel** [comment]
Uff, then it may be hard to find the root cause. Some ideas:
- PyInstaller/loader/rthooks/pyi_rth_pkgres.py points to FrozenImporter (in PyInstaller/loader/pyimod03_importers.py)
- Does the daemon change the current dir?
- Add `print()` statements to [`FrozenImporter.get_data()`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyimod03_importers.py#L459).
  - Is SYSPREFIX correct?
  - Is the `fullname` correct?
  - Is it in the archive's toc?
- For the development version we implemented [PEP-451 importers](https://www.python.org/dev/peps/pep-0451/] which may take some different path through the code.
  - Please try with Python 2.7 which for sure uses the PEP-302 importer
  - Please try PyInstaller 3.2.1, which does not implement the PEP-451 importer.

Good luck! If you find the cause, I'd appreciate a pull-request (and a test- case :-)

**Comment by mafrosis** [comment]
Hey, some responses and questions :)

* The daemon code does change the current directory by default - I disabled this feature and it made no difference.
* Python 2.7 exhibits the same bug, as does version 3.2.1.
* Current HEAD fails during install with a stacktrace (which is a separate issue). Working from the v3.2.1 tag is working fine.
* It seems from `print()` statements that `[FrozenImporter.get_data()](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/loader/pyimod03_importers.py#L454)` doesn't ever get called. I am likely doing something wrong here?

**Comment by htgoebel** [comment]
I can't tell, why the `print()` do not trigger - except that they trigger, but the output is discarded. Maybe you can adjust your daemon to write sys.stdout and sys.stderr to a file. (https://ubuntuforums.org/showthread.php?t=2263620 may be helpful for this.)

Beside this I think I found the reason (I hacked logging-statement into to pytz code :-): The extraction directory is gone when the daemon tries to access the resources.

 And me fool, there is already a reciepe for it: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-python-daemon-package

**Comment by htgoebel** [comment]
I have to admit that this does not solve the issue completely. But either this is the way to go or you simply can not use daemon with `--onefile`.

**Comment by mafrosis** [comment]
I spend six hours reading and debugging and you close the issue! :'(

* I did not literally mean `print()` statements - I'm using `logging` module as in my example code.=
* I found the recipe in [Recipe-python-daemon-package](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-python-daemon-package) early on and that did not fix this problem.
* My logging during the `pytz` code indicates that the `zonefile` directory exists in the pyinstaller binary. Archive viewer also confirms this.

I do not think this is invalid!

**Comment by htgoebel** [comment]
I spend several hour too until I discovered that simply the files are gone already. Just add `logger.info("%r", os.listdir(sys._MEIPATH))` to the try-clause in the daemon context to verify this.

But possible a workaround came to my mind (untested): You can add these file to the PYZ. For this after `Analysis` you need to move the files starting with `pytz` from `a.datas` to `a.zipped_data`. The .spec-file is a normal Python script so you can use the debugger (pdb) in there to learn more about this.

One word of warning: AFIAK `zipped_data` is not documented, thus there is a small chance this may change somewhen.

**Comment by htgoebel** [comment]
Addendum. I just grepped the source for `zipped_data` and found that PyInstaller [ought to collect these files](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/toc_conversion.py#L147) (called [here](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/build_main.py#L494) and put them into the PYZ.

**Comment by htgoebel** [comment]
I created an issue for solving the rood-cause #2717

**Comment by mafrosis** [comment]
Thank you @htgoebel, for all your hard work. I am unlikely to be of any help on this issue, but I will keep a close eye and test if/when some code is available.

**Comment by mafrosis** [comment]
@htgoebel It seems that my particular case with `DaemonContext` may be not be solved by #2717.

As I believe you also noticed - the `sys._MEIPATH` is removed once the `DaemonContext` is entered! This will surely mean it cannot work correctly.

The [Recipe-python-daemon-package](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-python-daemon-package) recipe doesn't fix this. I'll report back if I can come up with something.

**Comment by htgoebel** [comment]
> It seems that my particular case with DaemonContext may be not be solved by #2717.

After rethinking, I agree – the .exe including the archive will also be removed. But it would be only one file you would need to keep open. OTOH it would be interesting if the _MEIPASS directory will be removed then. Interesting case!

I's appreciate if you keep me informed, and even more if you'd update the receipt accordingly then. Thanks.
