### ISSUE TITLE
[pyttsx3] ImportError: No module named path

### ISSUE THREAD

**Issue by AlexPicaro** [pyinstaller/pyinstaller#3207]
An ImportError occurs at runtime after bundling an application using the pyttsx3 library. The error occurs when the text-to-voice engine is initialized, not when the library is imported:
```python
import pyttsx3             #This is fine
engine = pyttsx3.init()    #This causes the ImportError
```

PyInstaller builds the executable without any issue and as such, the log file is empty.
I am not using any Python distribution, only the base libraries and manually installed third-party libraries.

Platform details:
```
OS: Microsoft Windows [Version 10.0.16299.192]
>python --version
  2.7.13, 32-bit
>pyinstaller --version
  3.4.dev0+ab8fd9753
```

Here is a link to a gist containing the steps to reproduce, a sample program, the spec file and the stack trace: https://gist.github.com/AlexPicaro/aac977ead73c48a1e8e0d0d35f1a4cab

**Comment by Kerang** [comment]
Pyinstaller doesn't bundle everything it should when compiling the file. Pyttsx has hooks setup for it and was fixed. Pyttsx3 was created to support Python 3.X, I would recommend using pyttsx, if you're using Python 2.X. I've been banging my head on this problem for that couple of months or so. I just haven't had the hours to devote to it to track it all down.

**Comment by Kerang** [comment]
https://github.com/nateshmbhat/pyttsx3/issues/6

**Comment by Kerang** [comment]
I see that you're already collecting the submodules, so that's not the issue. It seems that your issue here, is directly related to the issue I was having.

[fixed / workaround for pyttsx3 test won't work once compiled with pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/3268)

I fixed it by creating a new hook-pyttsx3.py file which essentially does the same thing as your collect_submodules statement in your spec file.

Then, I also commented out all lines in the pyi_rth_win32comgenpy.py file. Should be located in the rthooks folder. C:\Users\YourUserName\AppData\Local\Programs\Python\YourPythonFolder\Lib\site-packages\Pyinstaller\loader\rthooks\
(Alternatively, you can just move the file and / or delete it.)

I'm guessing the pyi_rth_win32comgenpy.py hook is messing up something for you too.

**Comment by AlexPicaro** [comment]
Hey sorry I didn't respond to your first comment! The message got lost in my inbox. I tried that last solution you posted, and that solved my problem. Thanks a bunch!

I'm still having issues though, so I'll try pyttsx instead.

**Comment by Kerang** [comment]
What issue are you having?

**Comment by AlexPicaro** [comment]
Different import error, but I really don't know what to make of this one. Here's the stack trace:
```
 Traceback (most recent call last):
   File "main.py", line 96, in <module>
   File "site-packages\kivy\app.py", line 802, in run
   File "main.py", line 82, in build
   File "demoScreen.py", line 307, in __init__
   File "site-packages\pyttsx3\__init__.py", line 46, in init
     module.
   File "site-packages\pyttsx3\engine.py", line 52, in __init__
   File "site-packages\pyttsx3\driver.py", line 77, in __init__
   File "site-packages\pyttsx3\drivers\sapi5.py", line 22, in buildDriver
   File "site-packages\pyttsx3\drivers\sapi5.py", line 31, in __init__
   File "site-packages\win32com\client\__init__.py", line 317, in WithEvents

   File "site-packages\win32com\client\gencache.py", line 524, in EnsureModule
   File "site-packages\win32com\client\gencache.py", line 291, in MakeModuleForTypelib
   File "site-packages\win32com\client\makepy.py", line 286, in GenerateFromTypeLibSpec
   File "site-packages\win32com\client\gencache.py", line 554, in AddModuleToCache
   File "site-packages\win32com\client\gencache.py", line 633, in _GetModule
 ImportError: No module named C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4
[9856] Failed to execute script main
[9856] LOADER: OK.
[9856] LOADER: Cleaning up Python interpreter.
```

**Comment by Kerang** [comment]
Did you try commenting out all of the lines in the file `/site-packages/pyinstaller/loader/rthooks/pyi_rth_win32comgenpy.py` ?

pyi_rth_win32comgenpy.py file commented out:
```
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


# The win32.client.gencache code must be allowed to create the cache in %temp%
# (user's temp). It is necessary to get the gencache code to use a suitable
# directory other than the default in lib\site-packages\win32com\client\gen_py.
# PyInstaller does not provide this directory structure and the frozen
# executable could be placed in a non-writable directory like 'C:\Program Files.
# That's the reason for %temp% directory.
#
# http://www.py2exe.org/index.cgi/UsingEnsureDispatch


#import atexit
#import os
#import shutil
#import tempfile


# Put gen_py cache in temp directory.
#supportdir = tempfile.mkdtemp()
# gen_py has to be put into directory 'gen_py'.
#genpydir = os.path.join(supportdir, 'gen_py')


# Create 'gen_py' directory. This directory does not need
# to contain '__init__.py' file.
#try:
    # win32com gencache cannot be put directly to 'supportdir' with any
    # random name. It has to be put in a directory called 'gen_py'.
    # This is the reason why to create this directory in supportdir'.
 #   os.makedirs(genpydir)
    # Remove temp directory at application exit and ignore any errors.
  #  atexit.register(shutil.rmtree, supportdir, ignore_errors=True)
#except OSError:
 #   pass


# Override the default path to gen_py cache.
#import win32com
#win32com.__gen_path__ = genpydir


# The attribute __loader__ makes module 'pkg_resources' working but On Windows
# it breaks pywin32 (win32com) and test 'basic/test_pyttsx' will fail. Just
# removing that attribute for win32com fixes that and gencache is created properly.
#if hasattr(win32com, '__loader__'):
 #   del win32com.__loader__


# Ensure genpydir is in 'gen_py' module paths.
#import win32com.gen_py
#win32com.gen_py.__path__.insert(0, genpydir)
```

**Comment by AlexPicaro** [comment]
I did.

**Comment by Kerang** [comment]
Try uncommenting these two lines in the pyi_rth_win32comgenpy.py file:
```
#if hasattr(win32com, '__loader__'):
 #   del win32com.__loader__
```

**Comment by AlexPicaro** [comment]
I get the same stack trace as before.

**Comment by Kerang** [comment]
Did you make the pyttsx3 hook and comment out the pyi_rth_win32comgenpy.py fiel at the same time without testing in between?

It looks like the pyttsx3 hook is what fixed the module import error. I got a different win32com error and fixed it by commenting out the pyi_rth_win32comgenpy.py file.

It's possible, since you're using Python 2.X that you need the file uncommented like so:
```
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


# The win32.client.gencache code must be allowed to create the cache in %temp%
# (user's temp). It is necessary to get the gencache code to use a suitable
# directory other than the default in lib\site-packages\win32com\client\gen_py.
# PyInstaller does not provide this directory structure and the frozen
# executable could be placed in a non-writable directory like 'C:\Program Files.
# That's the reason for %temp% directory.
#
# http://www.py2exe.org/index.cgi/UsingEnsureDispatch


import atexit
import os
import shutil
import tempfile


# Put gen_py cache in temp directory.
supportdir = tempfile.mkdtemp()
# gen_py has to be put into directory 'gen_py'.
genpydir = os.path.join(supportdir, 'gen_py')


# Create 'gen_py' directory. This directory does not need
# to contain '__init__.py' file.
try:
    # win32com gencache cannot be put directly to 'supportdir' with any
    # random name. It has to be put in a directory called 'gen_py'.
    # This is the reason why to create this directory in supportdir'.
    os.makedirs(genpydir)
    # Remove temp directory at application exit and ignore any errors.
    atexit.register(shutil.rmtree, supportdir, ignore_errors=True)
except OSError:
    pass


# Override the default path to gen_py cache.
import win32com
win32com.__gen_path__ = genpydir


# The attribute __loader__ makes module 'pkg_resources' working but On Windows
# it breaks pywin32 (win32com) and test 'basic/test_pyttsx' will fail. Just
# removing that attribute for win32com fixes that and gencache is created properly.
if hasattr(win32com, '__loader__'):
    del win32com.__loader__


# Ensure genpydir is in 'gen_py' module paths.
import win32com.gen_py
win32com.gen_py.__path__.insert(0, genpydir)
```

**Comment by Kerang** [comment]
Ok, I noticed that you're using wine and as such are building the installer on a Linux machine.

Have you installed SAPI5 in wine? You won't be able to get pyttsx3 working in wine, if you don't have SAPI5 installed.

**Comment by Kerang** [comment]
You may be having issues with wine + pyinstaller. Python 2.7 + Win10 + Pyinstaller works with the pyttsx3 hook.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version.

**Comment by shafiqcseiu07** [comment]
?

**Comment by picoder007** [comment]
File "pi_coder_assistant.py", line 2, in <module>
    import pyttsx3
ImportError: No module named pyttsx3
