### ISSUE TITLE
how to solve the problem when package PyQt5

### ISSUE THREAD

**Issue by SongZhuhai** [pyinstaller/pyinstaller#3555]
```
  File "c:\program files\python36\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtCore.py", line 15, in <module>
    binaries = qt_plugins_binaries('codecs', namespace='PyQt5')
  File "c:\program files\python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 66, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\program files\python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 40, in qt_plugins_dir
    raise Exception('Cannot find {0} plugin directories'.format(namespace))
Exception: Cannot find PyQt5 plugin directories
```
The namespace's value isPyQt5, and my PyQt5 is up to date. 
Otherwise, my PyQt5 plugin directories is like this, "C:\Program Files\Python36\Lib\site-packages\PyQt5\Qt\plugins",  how can i solve this problem.
Can anyone help me, thanks!

**Comment by SongZhuhai** [comment]
I have import these
```
import numpy as np   
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import pandas as pd
```

**Comment by SongZhuhai** [comment]
I have solved this problem by changing source code. 
```
    if namespace == 'PyQt5':
        paths = ['C:/program files/python36/Lib/site-packages/PyQt5/Qt/plugins',
                 'C:/program files/python36']
```
This is because that fuction "eval_statement " can't parse the paths for PyQt5.
So when i add this code into "C:\Program Files\Python36\Lib\site-packages\PyInstaller\utils\hooks\qt.py" Line 38, the promblem is solved

**Comment by bjones1** [comment]
You're using an older version of PyInstaller. The current version of GitHub has improved detection code that should work.

**Comment by sethgilchrist** [comment]
This is still an issue with version 3.4 from Github. I had to manually put the path in, otherwise it picked up a path that didn't exist on my machine.

Win10
Anaconda3 - Python 2.7 env
PyInstaller 3.4

**Comment by CarlosAlberto18** [comment]
I have the problem with PyQt5 I have python 3.7.0 and pyinstaller 3.4 

File "D:\Anaconda\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "D:\Anaconda\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 514, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "D:\Anaconda\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "D:\Anaconda\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 117, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception: 
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/qt64/qt_1544645195969/_h_env/Library/plugins
help

**Comment by bjones1** [comment]
Use the development version -- this is fixed there.
