### ISSUE TITLE
ModuleNotFoundError: No moduel named 'PyQt5.sip'

### ISSUE THREAD

**Issue by Fryj2841** [pyinstaller/pyinstaller#3630]
Hello 

I am new to Pyinstaller but have ben able to successfully execute the code to build my exe file both in --onedir and --onefile.  I am using the latest version of Pyinstaller via pip install https://github.com/pyinstaller/pyinstaller/developer.zip.  Python version 3.6 via Andaconda distribution and latest PyQt5 package.  

Once compiled I tried to run the code and got the error ModuleNotFoundError: No module named 'PyQt5'.  Upon some research I found how to debug and this is the debug message.

```
import '_opcode' # <class '_frozen_importlib.BuiltinImporter'>
import 'opcode' # <_frozen_importlib_external.SourcelessFileLoader object at 0x0
000000002A5D278>
import 'dis' # <_frozen_importlib_external.SourcelessFileLoader object at 0x0000
000002A520F0>
# importlib.machinery not found in PYZ
# code object from 'C:\\Users\\fryj768\\Documents\\Test\\dist\\Ra_Gui\\importlib
\\machinery.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourcelessFileLoader
object at 0x0000000002A61AC8>
import 'inspect' # <_frozen_importlib_external.SourcelessFileLoader object at 0x
0000000002801908>
# pyfirmata.util not found in PYZ
# code object from 'C:\\Users\\fryj768\\Documents\\Test\\dist\\Ra_Gui\\pyfirmata
\\util.pyc'
# threading not found in PYZ
# code object from 'C:\\Users\\fryj768\\Documents\\Test\\dist\\Ra_Gui\\threading
.pyc'
import 'threading' # <_frozen_importlib_external.SourcelessFileLoader object at
0x0000000002A890B8>
# pyfirmata.boards not found in PYZ
# code object from 'C:\\Users\\fryj768\\Documents\\Test\\dist\\Ra_Gui\\pyfirmata
\\boards.pyc'
import 'pyfirmata.boards' # <_frozen_importlib_external.SourcelessFileLoader obj
ect at 0x0000000002A6ACF8>
import 'pyfirmata.util' # <_frozen_importlib_external.SourcelessFileLoader objec
t at 0x0000000002A63C50>
import 'pyfirmata.pyfirmata' # <_frozen_importlib_external.SourcelessFileLoader
object at 0x00000000027E8470>
import 'pyfirmata' # <_frozen_importlib_external.SourcelessFileLoader object at
0x000000000279F898>
# PyQt5 not found in PYZ
# code object from 'C:\\Users\\fryj768\\Documents\\Test\\dist\\Ra_Gui\\PyQt5\\__
init__.pyc'
import 'PyQt5' # <_frozen_importlib_external.SourcelessFileLoader object at 0x00
00000002801208>
# PyQt5.QtCore not found in PYZ
# PyQt5.sip not found in PYZ
Traceback (most recent call last):
  File "Ra_Gui.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyQt5.sip'
[7692] Failed to execute script Ra_Gui
[7692] LOADER: OK.
[7692] LOADER: Cleaning up Python interpreter.
# destroy PyQt5.QtCore
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing builtins
# cleanup[2] removing sys
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _warnings
# cleanup[2] removing _thread
# cleanup[2] removing _weakref
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing nt
# cleanup[2] removing winreg
# cleanup[2] removing zipimport
# cleanup[2] removing encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# cleanup[2] removing abc
# cleanup[2] removing _weakrefset
# destroy _weakrefset
# cleanup[2] removing struct
# cleanup[2] removing _struct
# cleanup[2] removing pyimod01_os_path
# cleanup[2] removing pyimod02_archive
# cleanup[2] removing zlib
# cleanup[2] removing pyimod03_importers
# cleanup[2] removing os
# cleanup[2] removing errno
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing ntpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# cleanup[2] removing ctypes
# cleanup[2] removing _ctypes
# cleanup[2] removing ctypes._endian
# cleanup[2] removing serial
# cleanup[2] removing importlib
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing types
# cleanup[2] removing functools
# cleanup[2] removing _functools
# cleanup[2] removing collections
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing _operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing heapq
# cleanup[2] removing _heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing weakref
# destroy weakref
# cleanup[2] removing collections.abc
# cleanup[2] removing warnings
# cleanup[2] removing serial.serialutil
# cleanup[2] removing time
# cleanup[2] removing serial.serialwin32
# cleanup[2] removing serial.win32
# cleanup[2] removing ctypes.wintypes
# cleanup[2] removing traceback
# cleanup[2] removing linecache
# cleanup[2] removing tokenize
# cleanup[2] removing re
# cleanup[2] removing enum
# cleanup[2] removing sre_compile
# cleanup[2] removing _sre
# cleanup[2] removing sre_parse
# cleanup[2] removing sre_constants
# destroy sre_constants
# cleanup[2] removing _locale
# cleanup[2] removing copyreg
# cleanup[2] removing token
# cleanup[2] removing pyfirmata
# cleanup[2] removing pyfirmata.pyfirmata
# cleanup[2] removing __future__
# destroy __future__
# cleanup[2] removing inspect
# cleanup[2] removing ast
# cleanup[2] removing _ast
# cleanup[2] removing dis
# cleanup[2] removing opcode
# destroy opcode
# cleanup[2] removing _opcode
# cleanup[2] removing importlib.machinery
# cleanup[2] removing pyfirmata.util
# cleanup[2] removing threading
# cleanup[2] removing pyfirmata.boards
# cleanup[2] removing PyQt5
# destroy PyQt5
# destroy _ast
# destroy zipimport
# destroy _signal
# cleanup[3] wiping _frozen_importlib
# cleanup[3] wiping _imp
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _weakref
# cleanup[3] wiping _frozen_importlib_external
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping nt
# cleanup[3] wiping winreg
# destroy winreg
# cleanup[3] wiping encodings
# destroy encodings.aliases
# destroy encodings.utf_8
# destroy encodings.latin_1
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping io
# cleanup[3] wiping abc
# cleanup[3] wiping struct
# cleanup[3] wiping _struct
# cleanup[3] wiping pyimod01_os_path
# cleanup[3] wiping pyimod02_archive
# cleanup[3] wiping zlib
# destroy zlib
# cleanup[3] wiping pyimod03_importers
# cleanup[3] wiping os
# destroy errno
# destroy ntpath
# cleanup[3] wiping stat
# cleanup[3] wiping _stat
# destroy _stat
# cleanup[3] wiping genericpath
# cleanup[3] wiping _collections_abc
# cleanup[3] wiping ctypes
# destroy _struct
# destroy ctypes._endian
# destroy ctypes.wintypes
# cleanup[3] wiping _ctypes
# cleanup[3] wiping serial
# destroy serial.serialutil
# destroy serial.serialwin32
# cleanup[3] wiping importlib
# destroy _frozen_importlib_external
# destroy importlib.machinery
# cleanup[3] wiping importlib._bootstrap
# cleanup[3] wiping types
# cleanup[3] wiping functools
# cleanup[3] wiping _functools
# cleanup[3] wiping collections
# destroy _collections_abc
# destroy heapq
# destroy collections.abc
# cleanup[3] wiping _operator
# cleanup[3] wiping _heapq
# cleanup[3] wiping itertools
# cleanup[3] wiping _collections
# destroy _collections
# cleanup[3] wiping warnings
# destroy _warnings
# cleanup[3] wiping time
# cleanup[3] wiping serial.win32
# cleanup[3] wiping traceback
# cleanup[3] wiping linecache
# cleanup[3] wiping tokenize
# destroy io
# cleanup[3] wiping re
# destroy sre_compile
# destroy copyreg
# cleanup[3] wiping enum
# destroy _operator
# destroy _functools
# cleanup[3] wiping _sre
# cleanup[3] wiping sre_parse
# cleanup[3] wiping _locale
# destroy _locale
# cleanup[3] wiping token
# cleanup[3] wiping pyfirmata
# destroy pyfirmata.boards
# destroy pyfirmata.pyfirmata
# cleanup[3] wiping inspect
# destroy abc
# destroy ast
# destroy dis
# destroy enum
# destroy importlib
# destroy linecache
# destroy re
# destroy tokenize
# destroy token
# destroy warnings
# destroy functools
# cleanup[3] wiping _opcode
# cleanup[3] wiping pyfirmata.util
# destroy threading
# destroy pyfirmata
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy stat
# destroy genericpath
# destroy nt
# destroy os
# destroy encodings
# destroy traceback
# destroy pyfirmata.util
# destroy ctypes
# destroy serial.win32
# destroy inspect
# destroy time
# destroy serial
# destroy _imp
# destroy _heapq
# destroy _thread
# destroy types
# destroy io
# destroy _opcode
# destroy _weakref
# destroy collections
# destroy itertools
# destroy _sre
# destroy sre_parse
# destroy _frozen_importlib
```

C:\Users\fryj768\Documents\Test\dist\Ra_Gui>

I am really lost and any help would be great

Thanks

**Comment by tallforasmurf** [comment]
Please edit your post and use the "code fence" syntax: triple back-ticks before and after computer output as [documented here](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code). That will make this mess readable.

**Comment by Fryj2841** [comment]
Sorry about that I'm new to git.

**Comment by htgoebel** [comment]
What command did you use for bundling the executable?

**Comment by Fryj2841** [comment]
pyinstaller --clean --onedir --debug myfile.py

**Comment by lamourj** [comment]
Not sure but it might be because since PyQt5 5.11, SIP is getting installed as a separate package, while that wasn't the case before (see [this](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html#downloading-sip)). 
I guess the issue there is that this change hasn't yet been taken into account in PyInstaller since it's very recent. Hope this helps.
I guess a hook would be welcome, but meanwhile you should just be able to add `PyQt5_sip` in the hidden imports.

**Comment by jhtitor** [comment]
Can confirm the same issue (and workaround) for PyQt 5.11. Wasn't the case with earlier PyQt5 versions (which bundled sip).

Adding `PyQt5.sip` to hidden imports fixes it.

**Comment by Fryj2841** [comment]
Thanks so much I will try it tonight.

**Comment by bjones1** [comment]
Thanks @jhtitor for pointing out the fix. I've tested a [branch](https://github.com/bjones1/pyinstaller/tree/pyqt5-fix) with this. While everything works in [Linux](https://travis-ci.org/bjones1/pyinstaller/builds/403694829) and Mac, there's several problems in [Windows](https://ci.appveyor.com/project/bjones1/pyinstaller/build/1.0.718) that the new PyQt5 versions seems to cause:

1. Python 3.6 32-bit doesn't seem to find QtWebEngineWidgets. It looks like the analysis code never invokes `hook-PyQt5.QtWebEngineWidgets`, even with a direct [from PyQt5.QtWebEngineWidgets import QWebEngineView](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py#L250). ???
2. `paths = [pyqt5_library_info.location['PluginsPath']]` reports a [key error](https://ci.appveyor.com/project/bjones1/pyinstaller/build/1.0.718/job/257g1bgfh5wn7g2l#L1426) on Python 3.5. ???

I don't have time to track this down -- please help!

**Comment by GeekPains** [comment]
Adding PyQt5.sip to the hidden imports helped to me, but doing this my application's GUI lost his own style (Windows): how this should look : how this looks.
![image](https://user-images.githubusercontent.com/41211681/42715856-d80706e0-8709-11e8-8f73-a37fdf5d58d1.png)

**Comment by htgoebel** [comment]
@GeekPains Please stop spaming issues with unrelated stuff. The theme has *nothing* to do with this issue.

**Comment by orangeSi** [comment]
@GeekPains just add `from PyQt5 import sip` to your python script, and repack it

**Comment by GeekPains** [comment]
@orangeSi that still doesn't fix my style problem. After repacking 'windowsvista' style goes away

**Comment by GeekPains** [comment]
I fixed losing style problem with uninstalling pyinstaller and installing the develop branch of pyinstaller: pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Thank y'all!

**Comment by The-Compiler** [comment]
@bjones1 
> Python 3.6 32-bit doesn't seem to find QtWebEngineWidgets

It doesn't exist - Qt 5.11 on Windows 32-bit doesn't ship with QtWebEngine at all (because the Chromium update needs MSVC 2017, and Qt doesn't have any official MSVC 2017 32-bit builds).

**Comment by bjones1** [comment]
@The-Compiler, thanks. I didn't realize this. I'd like to document this -- do you know of a nice link to some official Qt site that discusses this? I've Googled without success.

**Comment by bjones1** [comment]
@The-Compiler, thanks again. Both these problems are now fixed (or, at least, worked around), based on your input. See a2bda9a3ec98389badf79734faf835b01b7ebb4a and 7817d3facd341d3af1c1870a1f971170bcf4c6ac.

**Comment by vardhmanandroid2015** [comment]
Copying sip.pyd from folder PyQt5_sip-4.19.12-py3.7-win-amd64.egg to PyQt5-5.11.2-py3.7-win-amd64.egg did the trick for me.....It does not seem to be right approach but at least you will not stuck in waiting for fixes to come...Please let me know if still do not work....

**Comment by lamourj** [comment]
If you pull from the develop branch now, this should have been fixed.

On 19 Jul 2018, at 14:55, vardhmanandroid2015 <notifications@github.com<mailto:notifications@github.com>> wrote:


Copying sip.pyd from folder PyQt5_sip-4.19.12-py3.7-win-amd64.egg to PyQt5-5.11.2-py3.7-win-amd64.egg did the trick for me.....It does not seem to be right approach but at least you will not stuck in waiting for fixes to come...Please let me know if still do not work....
