### ISSUE TITLE
six.moves.queue.Full Attribute Error

### ISSUE THREAD

**Issue by lucabianchi91** [pyinstaller/pyinstaller#4897]
Hi,
while building an an application, a pre-safe-import-module hook failed.
* Output of `pyinstaller --version`: 4.0.dev0
* Output of `pyinstaller ${myproject}.spec`:
```43 INFO: PyInstaller: 4.0.dev0
42 INFO: PyInstaller: 4.0.dev0
42 INFO: Python: 3.6.9
43 INFO: Platform: Linux-5.4.0-31-generic-x86_64-with-Ubuntu-18.04-bionic
44 INFO: UPX is not available.
45 INFO: Extending PYTHONPATH with paths
['/root/humanitas/simulation_orchestrator',
 '/root/humanitas/docker_manager',
 '/root/humanitas/heaven_py3',
 '/root/humanitas/api_manager',
 '/usr/local/lib/python3.6/dist-packages/eventlet']
48 INFO: checking Analysis
53 INFO: Building because pathex changed
53 INFO: Initializing module dependency graph...
55 INFO: Caching module graph hooks...
62 INFO: Analyzing base_library.zip ...
3443 INFO: Caching module dependency graph...
3549 INFO: running Analysis Analysis-00.toc
3583 INFO: Analyzing simulation_orchestrator.py
3814 INFO: Processing pre-find module path hook distutils from '/usr/local/lib/python3.6/dist-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
3815 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.6'
3848 INFO: Processing pre-safe import module hook six.moves from '/usr/local/lib/python3.6/dist-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
5708 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/usr/local/lib/python3.6/dist-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 28, in <module>
    from .packages.six.moves import queue
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/queue.py", line 60, in <module>
    Full = six.moves.queue.Full
AttributeError: module 'queue' has no attribute 'Full'
pre-safe-import-module hook failed, needs fixing.
```
* Version of Python: 3.6.9
* Platform: e.g GNU/Linux (Ubuntu 18.04)
* Installation is clean and packages are updated (this is running inside a container)
```
# pip list -v
Package          Version    Location                               Installer
---------------- ---------- -------------------------------------- ---------
altgraph         0.17       /usr/local/lib/python3.6/dist-packages pip
asn1crypto       0.24.0     /usr/lib/python3/dist-packages
certifi          2020.4.5.1 /usr/local/lib/python3.6/dist-packages pip
cffi             1.14.0     /usr/local/lib/python3.6/dist-packages pip
chardet          3.0.4      /usr/local/lib/python3.6/dist-packages pip
cryptography     2.1.4      /usr/lib/python3/dist-packages
dnspython        1.16.0     /usr/local/lib/python3.6/dist-packages pip
docker           4.2.0      /usr/local/lib/python3.6/dist-packages pip
eventlet         0.25.2     /usr/local/lib/python3.6/dist-packages pip
greenlet         0.4.15     /usr/local/lib/python3.6/dist-packages pip
idna             2.6        /usr/lib/python3/dist-packages
ipaddress        1.0.23     /usr/local/lib/python3.6/dist-packages pip
keyring          10.6.0     /usr/lib/python3/dist-packages
keyrings.alt     3.0        /usr/lib/python3/dist-packages
licensing        0.15       /usr/local/lib/python3.6/dist-packages pip
monotonic        1.5        /usr/local/lib/python3.6/dist-packages pip
pip              20.1.1     /usr/local/lib/python3.6/dist-packages pip
psutil           5.7.0      /usr/local/lib/python3.6/dist-packages pip
pycparser        2.20       /usr/local/lib/python3.6/dist-packages pip
pycrypto         2.6.1      /usr/lib/python3/dist-packages
pygobject        3.26.1     /usr/lib/python3/dist-packages
pyinstaller      4.0.dev0   /usr/local/lib/python3.6/dist-packages pip
pyOpenSSL        19.1.0     /usr/local/lib/python3.6/dist-packages pip
python-engineio  3.13.0     /usr/local/lib/python3.6/dist-packages pip
python-socketio  4.6.0      /usr/local/lib/python3.6/dist-packages pip
pyxdg            0.25       /usr/lib/python3/dist-packages
PyYAML           5.3.1      /usr/local/lib/python3.6/dist-packages pip
requests         2.23.0     /usr/local/lib/python3.6/dist-packages pip
SecretStorage    2.3.1      /usr/lib/python3/dist-packages
setuptools       46.4.0     /usr/local/lib/python3.6/dist-packages pip
six              1.15.0     /usr/local/lib/python3.6/dist-packages pip
urllib3          1.25.9     /usr/local/lib/python3.6/dist-packages pip
websocket-client 0.57.0     /usr/local/lib/python3.6/dist-packages pip
wheel            0.34.2     /usr/local/lib/python3.6/dist-packages pip
xmltodict        0.12.0     /usr/local/lib/python3.6/dist-packages pip
```
I've added  `/usr/local/lib/python3.6/dist-packages/eventlet` to `pathex` because, if I don't do so,
the build goes through but at runtime I get the error
```
File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
```
Any hint on how to fix the hook?
Many thanks

**Comment by Legorooj** [comment]
I've just spent half an hour hacking away at this. I can't reproduce this at all.

**Comment by lucabianchi91** [comment]
Hi, 
I have reduced the project to the bare minimum (5 files) and uploaded it here [build_test](https://github.com/lucabianchi91/build_test) to allow to reproduce the issue.

To reproduce the build issue, clone and run
`docker build -t build_test .`

This should result in `AttributeError: module 'queue' has no attribute 'Full'`

If `eventlet` is removed from `pathex`, build succed, but
`docker run -it --rm build_test` will fail at runtime with 
```
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
[6] Failed to execute script build_test
```
Please note that the script works fine with the interpreter.
To verify it:
```
docker run -it --rm --entrypoint="" build_test python3 /root/build_test/build_test.py
```

Thank you again for your time

**Comment by docon92** [comment]
Any updates on this? I am having the same issue!

**Comment by Legorooj** [comment]
@docon92 @lucabianchi91 I haven't had a chance to reproduce this yet. Hopefully I'll get to it in a few days.

**Comment by lucabianchi91** [comment]
If this can help, I found a way around the issue, i.e. adding the missing package to `hiddenimports` and retry until I got to the following list:  
```a = Analysis(['build_test.py'],
             pathex=[],
             binaries=[],
             datas=[],
             hiddenimports=[
             'eventlet', 'eventlet.hubs.epolls', 'eventlet.hubs.kqueue', 'eventlet.hubs.selects', 
             'dns', 'dns.dnssec', 'dns.e164', 'dns.hash', 'dns.namedict','dns.tsigkeyring', 'dns.update', 'dns.version', 'dns.zone',
             'engineio.async_drivers.threading'
             ],
```
and adding `import eventlet.wsgi` after `import eventlet` in the code.

**Comment by Legorooj** [comment]
@lucabianchi91 that's great! The hook still needs fixing though, and I'm having docker troubles. I need to fix those then I'll trace, reproduce, and fix this.

**Comment by Legorooj** [comment]
@lucabianchi91 It appears I have a problem with docker: https://github.com/docker/for-win/issues/3597. I'm getting that error and I'm unable to get docker working. Could you try and track this down more or find another way for me to reproduce? Maybe a CI build?

**Comment by lucabianchi91** [comment]
Sure! Docker was the simplest way I know to run pyinstaller in a clean environment, but I guess that also a VM will do. 
I will try to install the pip packages listed in the Dockerfile and run pyinstaller in a new Ubuntu18 VM and let you know.

**Comment by lucabianchi91** [comment]
`pyinstaller build_test.spec` doesn't give errors but the when I run the generated file (`dist/build_test/build_test`) I get the same `eventlet.hub.epolls` error.

**Comment by bwoodsend** [comment]
@Legorooj I'm able to reproduce the error using lucabianchi91's docker build.

@lucabianchi91 Could you explain what `pathex=[/usr/local/lib/python3.6/dist-packages/eventlet'],` is doing in the spec. Removing it fixed the build error.

**Comment by lucabianchi91** [comment]
@bwoodsend  As I wrote in my first message: 
> I've added /usr/local/lib/python3.6/dist-packages/eventlet to pathex because, if I don't do so,
the build goes through but at runtime I get the error
File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'

and second message:

> If eventlet is removed from pathex, build succed, but
docker run -it --rm build_test will fail at runtime with
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
[6] Failed to execute script build_test

**Comment by bwoodsend** [comment]
@lucabianchi91 Ahh so you did. But in the spec file in the repo you've shared you then put `eventlet.hubs.epolls` into `hiddenimports` (which is the correct way to fix `ModuleNotFoundError`s at runtime). When I ran your docker it built and ran fine if I removed the `pathex` and kept the long `hiddenimports=[...]` list. Does it not work like that for you?

**Comment by lucabianchi91** [comment]
> If this can help, I found a way around the issue, i.e. adding the missing package to `hiddenimports` and retry until I got to the following list:
> 
> ```
>              pathex=[],
>              binaries=[],
>              datas=[],
>              hiddenimports=[
>              'eventlet', 'eventlet.hubs.epolls', 'eventlet.hubs.kqueue', 'eventlet.hubs.selects', 
>              'dns', 'dns.dnssec', 'dns.e164', 'dns.hash', 'dns.namedict','dns.tsigkeyring', 'dns.update', 'dns.version', 'dns.zone',
>              'engineio.async_drivers.threading'
>              ],
> ```
> 
> and adding `import eventlet.wsgi` after `import eventlet` in the code.

@bwoodsend  This means it compile and run fine. But as @Legorooj said

> @lucabianchi91 that's great! The hook still needs fixing though, and I'm having docker troubles. I need to fix those then I'll trace, reproduce, and fix this.

one is not supposed to add all those hiddenimports to make it work.

**Comment by bwoodsend** [comment]
> one is not supposed to add all those hiddenimports to make it work.

Of course yes. I was just asserting that we agree on the issue and the changes needed to be made to the hook before I start changing things. I'll write it now.

Just to confirm:

- That list of hidden imports.
- Work out what to do with `import eventlet.wsgi`.

And don't extend `path_ex`.

**Comment by bwoodsend** [comment]
Ok, I think I've fixed it in my fork. @lucabianchi91 can you:

- `pip install https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip`.
- Comment out or remove all your patch fixes (the hidden imports and the `import eventlet.wsgi`).
- Then rebuild your program (please use the `--clean` option).

You will get a huge pile of warnings about multiple hooks for the same module but it should all work out apart from that. At least it does for me in docker.

**Comment by Legorooj** [comment]
@bwoodsend just a recommendation: don't develop on the master branch. We use that for stable releases only, so a PR from the master branch of a fork will confuse us. Use descriptive branch names where possible.

**Comment by Legorooj** [comment]
@lucabianchi91

**Comment by lucabianchi91** [comment]
This pyinstaller does not get even installed
```
root@4e9cf5bf54e6:~/build_test# python3 -m pip install https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip
Collecting https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip
  Using cached https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied (use --upgrade to upgrade): pyinstaller-hooks-contrib==2020.6 from https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip in /usr/local/lib/python3.6/dist-packages
Building wheels for collected packages: pyinstaller-hooks-contrib
  Building wheel for pyinstaller-hooks-contrib (PEP 517) ... done
  Created wheel for pyinstaller-hooks-contrib: filename=pyinstaller_hooks_contrib-2020.6-py2.py3-none-any.whl size=151044 sha256=c450747ee142a601c9299a3e32cc16538874705191b16c2189e8adb62fdedf4c
  Stored in directory: /tmp/pip-ephem-wheel-cache-68yvbbnu/wheels/22/db/69/3b40a37de338b4072b61fcb02e09b6fefa41d2a25e56f1d211
Successfully built pyinstaller-hooks-contrib
root@4e9cf5bf54e6:~/build_test# pyinstaller --noconfirm build_test.spec
bash: pyinstaller: command not found
```

**Comment by lucabianchi91** [comment]
Does `https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip` have to be installed after the dev version?
Because if installed alone, pyinstaller is command not found.
I did so, cleaned spec as requested, but I still get:
```
$ docker run -it --rm build_test
Traceback (most recent call last):
  File "build_test.py", line 2, in <module>
    import eventlet
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "eventlet/__init__.py", line 10, in <module>
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "eventlet/convenience.py", line 4, in <module>
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "eventlet/greenpool.py", line 4, in <module>
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "eventlet/queue.py", line 49, in <module>
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "eventlet/event.py", line 3, in <module>
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "eventlet/hubs/__init__.py", line 19, in <module>
  File "eventlet/hubs/__init__.py", line 19, in <genexpr>
  File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
[6] Failed to execute script build_test
```

**Comment by Legorooj** [comment]
@lucabianchi91 can you post the build log? The latest one with @bwoodsend's changes.

**Comment by bwoodsend** [comment]
Actually it looks like I've forced pushed sometime between now and when I did this as the changes are gone. Completely forgot we hadn't finished with this one. I'll reproduce them in a new branch. @lucabianchi91 I'll give you the go ahead when I'm ready for you to test them...

**Comment by bwoodsend** [comment]
Ughh. I'm talking nonsense. The changes are still online - I just cleared them locally. I had to add a `-U` to the `pip3 install https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip` or it ignores it. 

My `Dockerfile` (which is working for me) currently is:

```docker
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    python3-dev

RUN python3 -m pip install --upgrade pip setuptools wheel
RUN pip3 install \
	urllib3 \
	requests \
	python-socketio \
	eventlet
	
WORKDIR /root/build_test
COPY . .
RUN pip3 install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip
RUN pip3 install -U https://github.com/bwoodsend/pyinstaller-hooks-contrib/archive/master.zip
RUN rm -rf build dist
RUN pyinstaller --noconfirm --clean build_test.spec
RUN dist/build_test/build_test
ENTRYPOINT ["/root/build_test/dist/build_test/build_test"]
```

**Comment by bwoodsend** [comment]
@lucabianchi91 Can you try my branch again?

**Comment by lucabianchi91** [comment]
Ok, it worked. Some notes for future tests with docker:
- `RUN dist/build_test/build_test` should not be run in the Dockerfile (`docker build` is to build an image - i.e. setup an environment, build code etc. - not to run processes. For that you have `docker run`)
- I guess you added `RUN rm -rf build dist` and `--clean` because you also tried to run `pyinstaller` on bare metal first. You can directly avoid copying `build` and `dist` in the image by adding them to the `.dockerignore`. 
- I noticed that `git clone` does not always clone the latest code, but sometimes it uses cache (so, I was cloning old stuffs and it was not working). I think that [this](https://github.com/moby/moby/issues/1996#issuecomment-172606763) is the best solution around

**Comment by bwoodsend** [comment]
Ok, good to hear. And, as you can probably tell, my understanding of docker goes as far as `docker run command` - I didn't even know you could write scripts like that until this issue. 

I'll keep this issue open until merging my fixes into the main repo - otherwise I'll probably about this...

**Comment by bwoodsend** [comment]
@Legorooj Should we not transfer this to the hooks repo?

**Comment by Legorooj** [comment]
@bwoodsend no - and I'm not even sure that this issue will be relevant after ModuleGraph2. I didn't realize until I started on it 🙄. I'll self-assign this and add it to the modgraph2 project so I gets dealt with during the switch. If you could leave your changes that would be great.
