### ISSUE TITLE
Unable to use --noconsole and --onefile at a time

### ISSUE THREAD

**Issue by AhsanSheraz** [pyinstaller/pyinstaller#4930]
Python version: 3.8
Pyinstaller version: 3.6
OS: Windows 10

I tried different processes to convert a .py file into .exe:

**1:(works fine)** The first process is "pyinstaller --noconsole myprogram.py". It works fine no console, an exe file with all dll's.

**2:(works fine)** The second process is "pyinstaller --onefile myprogram.py". It's also working fine a single exe file, when execute an exe file a console appears and everything goes as expected.

**3:(issue)** In this process i used onefile and noconsle at same time "pyinstaller --onefile --noconsole myprogram.py". it genrates a single exe file, and when i try to open the exe file it pop-up "Failed to execute script".

I am using tkinter in my code, and run multiple terminal commands using "subprocess.run and os.popen".
I also try to --debug=all option with this exe pop-up "Failed to execute script pyiboot01_bootstrap."

**Same issue no help:** [Please look at this issue](https://stackoverflow.com/questions/56532453/pyinstaller-exe-unable-to-create-onefile-and-noconsole-at-same-time)

**Comment by Legorooj** [comment]
Can you try the latest development version? `pip install -U https://github.com/pyinstaller/pyinstaller`. I have used both of these options together in the last 2 days locally FYI.

**Comment by AhsanSheraz** [comment]
Yes...

**Comment by chen-gz** [comment]
I have same issue.

**Comment by ottogutierrez** [comment]
Has anyone made this work yet? Just to check, no console is the same as -w command right?

**Comment by AhsanSheraz** [comment]
> Has anyone made this work yet? Just to check, no console is the same as -w command right?

not yet. Unable to figure this out. why it's not working.

**Comment by ottogutierrez** [comment]
I just fixed it for my setup. What happened was that I was using (on spec file) the debug for the imports, so that needed a console. I read somewhere that you need to make sure that you are not using (anywhere in your code or spec file) any console dependent functions, otherwise you will get errors.

Let me know if this helps for you.

**Comment by chen-gz** [comment]
I found this issue happened when work with Gitpython.  I don't now how to solve it.

**Comment by Legorooj** [comment]
@AhsanSheraz I've been unable to reproduce this locally. If anyone else can figure out what's causing the issue that would be a step towards fixing it.

**Comment by AhsanSheraz** [comment]
> I just fixed it for my setup. What happened was that I was using (on spec file) the debug for the imports, so that needed a console. I read somewhere that you need to make sure that you are not using (anywhere in your code or spec file) any console dependent functions, otherwise you will get errors.
> 
> Let me know if this helps for you.

@ottogutierrez I know but there are alot of commands that I need to run through cmd in python script. Than what I do for this?

**Comment by AhsanSheraz** [comment]
> @AhsanSheraz I've been unable to reproduce this locally. If anyone else can figure out what's causing the issue that would be a step towards fixing it.

@Legorooj thanks for your response. But I still facing this issue if you have some commands run using subprocess.popen and you also have some tkinter code in your script than you will be able to reproduce this issue, with the above process. At that point you will not be able to successfully created a fully runable exe file. You will have some errors like some import issues or after running some commands exe will be crashed silently.

**Comment by Legorooj** [comment]
@AhsanSheraz I used a small tkinter dialog which displayed the python version, which was gotten through `Popen`. It worked fine. Can you send me some code that causes the issue for you?

**Comment by htgoebel** [comment]
> I am using tkinter in my code, and run multiple terminal commands using "subprocess.run and os.popen".

Please try with a simple "print(42)" script.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.

**Comment by georgehulme2** [comment]
Still having this issue nearly 2 months later...

I know Python27 should now be dead in the water but my clients insisted...

Stack trace:
  File "cryptolens_python2.py", line 382, in GetMachineCode
  File "cryptolens_python2.py", line 161, in start_process
  File "subprocess.py", line 386, in __init__
  File "subprocess.py", line 509, in _get_handles
WindowsError: [Error 6] The handle is invalid

**Comment by bwoodsend** [comment]
@georgehulme2 If you can provide a minimal example which gives this error then we can re-open and resume. Otherwise this issue continues to go nowhere...

**Comment by georgehulme2** [comment]
Any usage of Helpers.GetMachineCode when pyinstaller compiles the project with the tags (--noconsole || --windowed) && --onefile

**Comment by georgehulme2** [comment]
Here is the offending function

`def ActivateLicenseKey(key=None, is_floating=False, friendly_name=None):
	auth, RSAPubKey, product_id = GetDefaultLicenseCredentials()
	if is_floating:
		result = Key.activate(token=auth, rsa_pub_key=RSAPubKey, product_id=product_id, key=key, machine_code=Helpers.GetMachineCode(), floating_time_interval=300, friendly_name=friendly_name)
	else:
		result = Key.activate(token=auth, rsa_pub_key=RSAPubKey, product_id=product_id, key=key, machine_code=Helpers.GetMachineCode(), friendly_name=friendly_name)

	if result[0] == None or not Helpers.IsOnRightMachine(result[0], is_floating_license=is_floating):
		raise UserWarning("The license does not work: {0}".format(result[1]))
	else:
		if __name__ == '__main__':
			print("The license is valid.")

		return result`

**Comment by chen-gz** [comment]
When I using gitpython and pyqt simultaneously, I have same issue.
________________________________

**Comment by rokm** [comment]
I think in @georgehulme2 case, the culprit is [`start_process` method in `cryptolens`](
https://github.com/Cryptolens/cryptolens-python/blob/8f6ce7ff37c1cc1b6ed1fac2c0f9200702304d98/cryptolens_python2.py#L158-L164):
```python
    @staticmethod    
    def start_process(command):
        
        process = Popen(command, stdout=PIPE)
        (output, err) = process.communicate()
        exit_code = process.wait()
        return output.decode("utf-8")
```
The Popen call does not redirect `stdin` nor `stderr`, so they are inherited from parent, and in `noconsole` version, probably invalid.

**Comment by georgehulme2** [comment]
> I think in @georgehulme2 case, the culprit is [`start_process` method in `cryptolens`](https://github.com/Cryptolens/cryptolens-python/blob/8f6ce7ff37c1cc1b6ed1fac2c0f9200702304d98/cryptolens_python2.py#L158-L164):
> 
> ```python
>     @staticmethod    
>     def start_process(command):
>         
>         process = Popen(command, stdout=PIPE)
>         (output, err) = process.communicate()
>         exit_code = process.wait()
>         return output.decode("utf-8")
> ```
> 
> The Popen call does not redirect `stdin` nor `stderr`, so they are inherited from parent, and in `noconsole` version, probably invalid.

Yeah, I'm already playing around with it
Should have a fix in just a bit

**Comment by georgehulme2** [comment]
So I've managed to fix it on my end; no console, flashing or otherwise. The code is not pretty and definitely not permanent, but it works so, what the hay...

I'll post the fix in a couple of minutes when I review the diff

**Comment by georgehulme2** [comment]
---IMPORTS---
REMOVED
`
21   from subprocess import Popen, PIPE
`
ADDED
`
21   from sys import platform as pltfm
22   if pltfm == "win32":
23       from subprocess import check_output, PIPE, STARTUPINFO, STARTF_USESHOWWINDOW
24   else:
25       from subprocess import check_output, PIPE
`
---FUNCTION 'start_process'---
REMOVED
`
160  
161          process = Popen(command, stdout=PIPE)
162          (output, err) = process.communicate()
163          exit_code = process.wait()
164          return output.decode("utf-8")
`
ADDED
`
164          if pltfm == "win32":
165              class STARTUPINFO:
166                  dwFlags = 0
167                  hStdInput = None
168                  hStdOutput = None
169                  hStdError = None
170                  wShowWindow = 0
171  
172              startupinfo = STARTUPINFO()
173              startupinfo.dwFlags |= STARTF_USESHOWWINDOW
174          else:
175              startupinfo=None
176  
177          return check_output(command, startupinfo=startupinfo, stdin=PIPE, stderr=sys.stderr).wait()
`

**Comment by georgehulme2** [comment]
[cryptolens_python2.zip](https://github.com/pyinstaller/pyinstaller/files/5300059/cryptolens_python2.zip)

**Comment by georgehulme2** [comment]
Before anyone asks, for some reason python wouldn't let me just use the STARTUPINFO() class from subprocess, so I just flat out copy and pasted the thing in there

**Comment by georgehulme2** [comment]
@rokm if you could have a look, I don't think this affects the nature of the program other than hiding the flashing command prompt. It may do in some unexpected way however. Let me know

**Comment by rokm** [comment]
That does look like one of possible solutions (the other apparently being redirecting the stdin via `stdin` argument, although the exact way differs between python 2 and 3).

At any rate, this is not a pyinstaller issue, but rather something that needs to be fixed in `cryptolens` - either in your copy or their upstream. In the latter case, it'll be up to them to decide the preferred way to fix this.

**Comment by PGBRULES** [comment]
Nearly 3 months later, still having an issue with this :)
`pyinstaller --onefile --name undetectable --key 1234567890123456 --upx-dir E:\downloads\upx-3.96-win64\upx-3.96-win64 --uac-admin --upx-exclude=vcruntime140.dll --clean --noconsole server.py` is the command I used to generate the EXE
My code works fine without the --noconsole option. I am not printing to the console in my code. When I run the program I get "Failed to execute script server"

**Comment by Legorooj** [comment]
Please open a new issue.
