### ISSUE TITLE
Polarion Session Error after running the executable

### ISSUE THREAD

**Issue by krishtej23** [pyinstaller/pyinstaller#6403]
## Description of the issue
I have a python script to connect to polarion and perform some operations. I used PyCharm IDE and everything works completely fine when I run the script in the IDE but when I build the executable using pyinstaller, I am getting the below error. I get the same error with upx false and debug true.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: ```Python 3.9.2```
* Platform: ```Windows```
* How you installed Python: ```PyCharm```
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from polarion import polarion
from getpass import getpass

server = 'https://server/'
username = input("Enter UserId: ")
pwd = getpass()


try:
    ps = polarion.Polarion(server, username, pwd)
except:
    print("Unable to connect to Polarion server. Please try again later")
else:
    projID = input("Please enter the project ID: ")
    projectObj = ps.getProject(projID)

    print("Parent ID:")
```

### Stacktrace / full error message

```
Enter UserId: ABC1234
Password:
Unable to connect to Polarion server. Please try again later
Exception ignored in: <function Polarion.__del__ at 0x0000025164881B80>
Traceback (most recent call last):
  File "polarion\polarion.py", line 43, in __del__
KeyError: 'Session'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by krishtej23** [comment]
@bwoodsend I updated the issue based on the template.

**Comment by bwoodsend** [comment]
That's more like it. I can't reproduce this without credentials so you're going to have to do the heavy lifting. Can you get rid of the `try: except:` clause that's silencing the error - it's that traceback it's hiding that we need.

```python
ps = polarion.Polarion(server, username, pwd)

projID = input("Please enter the project ID: ")
projectObj = ps.getProject(projID)

print("Parent ID:")
```
Then run it again and share the new stacktrace.

**Comment by bwoodsend** [comment]
Also can you confirm the version of polarion that you are using? I grabbed the latest but the line numbers don't match so I don't think it's what you have.

**Comment by krishtej23** [comment]
I am using `0.1.14` version of polarion. Without the pyinstaller, when I run the code in PyCharm, script can make the connection but the below error pops up when running the executable.
```
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "polarion-playground.py", line 8, in <module>
  File "polarion\polarion.py", line 38, in __init__
  File "polarion\polarion.py", line 57, in _getServices
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='server', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
[19768] Failed to execute script 'polarion-playground' due to unhandled exception!
Exception ignored in: <function Polarion.__del__ at 0x000002650E051B80>
Traceback (most recent call last):
  File "polarion\polarion.py", line 43, in __del__
KeyError: 'Session'
```

**Comment by krishtej23** [comment]
By seeing the error, I realized that sometime in June, there was some issue with certification and Rok Mandeljc helped with this solution, [https://github.com/pyinstaller/pyinstaller/discussions/5919#discussioncomment-879412](). 
By adding the below code, current issue is resolved too. I do NOT see any error. Is this something pyinstaller need to be updated with?
```
import sys
if getattr(sys, 'frozen', False) and sys.platform == 'win32':
    import certifi
    import certifi_win32.wincerts
    
    certifi_win32.wincerts.CERTIFI_PEM = certifi.where()
    
    certifi.where =  certifi_win32.wincerts.where
    
    from certifi_win32.wincerts import generate_pem, verify_combined_pem
    if not verify_combined_pem():
        generate_pem()
```

**Comment by bwoodsend** [comment]
Ughh, I suppose it could be a runtime hook for python-certifi-win32 over on [the hooks repo](github.com/pyinstaller/pyinstaller-hooks-contrib/) which would fix both this issue and your troubles on #5919 (although IMO python-certifi-win32 cleaning up their hackery would be the correct solution).

**Comment by rokm** [comment]
Even if we added a runtime hook, we'd still need to have people activate it manually via an added hiddenimport, because `python-certifi-win32` bootstraps itself via .pth file, so none of its modules appear in the application's modulegraph. Which means that frozen programs relying on Windows certificate store still won't work out of the box, nor will debugging of issues such as this one be any easier. Plus, we'd need a stdhook to ensure that the imports made by rthook are collected.

So at the end of the day, once people do manage to figure out that their issues are due to missing certificates from Windows cert store that were available via `certifi_win32` in the unfrozen version, we'd only be saving them from having to include those ten lines of code at the start of their program - which make the dependency much more obvious, and also ensure that the required modules appear in the modulegraph.

**Comment by bwoodsend** [comment]
I guess that's a no then. We can't do anything about it except redirect people here until certifi_win32 find a more conventional way of exposing certificates.
