### ISSUE TITLE
`hide_console` options don't work on Windows 11

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#8022]
## Description of the issue
Based on #8006 I applied `hide_console=hide-early`, which worked great on my Windows 10 device.
However, users quickly reported that on Windows 11 it does not work, the window just stays open.
I tested it on a Windows 11 laptop, and they seem to be right.

I also tested the other options, like `minimize-early`, but they also didn't seem to work.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 3.11
* Platform: Windows 11
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Windows 10 works
* I also tried PyInstaller development version.

### A minimal example program which shows the error

```python
import time

print("hello")
time.sleep(30)
```

```
 pyinstaller scratch.py --hide-console=hide-early --console
```

**Comment by rokm** [comment]
Hmmm, looks like `ShowWindow` does not work with the shiny new Windows Terminal. Not sure if we can do anything about it, though - aside from putting a warning into documentation.

According to https://github.com/microsoft/terminal/issues/12570, this was addressed in `v1.14.143`, but then `v1.14.145` added https://github.com/microsoft/terminal/pull/13164, and it seems that by now (`1.17.11461.0`) neither hide nor minimize (even with `SW_MINIMIZE` (6) instead of `SW_SHOWMINNOACTIVE` that we currently use) works. https://github.com/microsoft/terminal/issues/12464 seems to be the current issue for `SW_HIDE`.

If you are creating launcher shortcuts for your users, you might be able to work-around this by explicitly launching the application via old `conhost`, as described here: https://github.com/nzbget/nzbget/issues/792#issuecomment-1093350550

**Comment by buzzwebly** [comment]
Here's a fix for this, it involves setting the Windows 11 Terminal app to default to 'Windows Console Host' instead of 'Windows Terminal' on startup. It's default is Let Windows Decide and it appears to always "decide" on Windows Terminal.

- Open Terminal

- To the right of any existing tabs, right click on a blank area of the tab bar 
 (or left click on the drop down symbol next to the + sign)
  in either case then choose Settings

- Once in settings, set 'Default terminal application' to 'Windows Console Host'

- 'Save' settings

- Did you remember to save settings? 

After doing the above, SABnzbd will start correctly without leaving a terminal window
open.

Note these are *not* the same set of settings found for Terminal in the app list, so if you can't find it, maybe that's where you went looking. Do the above.

A permanent solution should still be sought since Microsoft will likely remove this option at some point in the future in a bid to get rid of the old console host, but I don't imagine that happening until they've at least fixed the known bugs in Terminal referred to in the earlier posts here. On the other hand, we are talking about Microsoft ;-)

**Comment by rtommy** [comment]
I have done some testing recently and it seems there is still an issue with Windows Terminal.

- pyinstaller: 6.9.0 (`onedir` compilation) 
- python: 3.12.4
- Windows 11 version 23H2
- Windows Terminal: 1.20.11781.0

Default terminal application: Windows Console Host (`conhost.exe`)
The `hide_console` (`hide-early` or `minimize-early`) works as expected with `conhost`.

But issues could be seen when I used `Let Windows decide` or `Windows Terminal` (`wt.exe`).

I recompiled the `bootloader` for testing. I edited the following function and simply added some debug to it.
(I used `WARNING` so then I could eliminate all the `DEBUG` messages)

```
pyi_utils_win32.c

static void pyi_win32_adjust_console(int show_cmd)
{
...
            succeeded = ShowWindow(hConsole, show_cmd);
            PYI_WARNING("LOADER: 1. IsWindowVisible: %d\n", IsWindowVisible(hConsole));
            PYI_WARNING("LOADER: 1. ShowWindow updated: %d\n", succeeded);
            if (!succeeded) {
                succeeded = ShowWindow(hConsole, show_cmd);
                PYI_WARNING("LOADER: 2. IsWindowVisible: %d\n", IsWindowVisible(hConsole));
                PYI_WARNING("LOADER: 2. ShowWindow updated: %d\n", succeeded);
            }
            if (!succeeded) {
                succeeded = ShowWindow(hConsole, show_cmd);
                PYI_WARNING("LOADER: 3. IsWindowVisible: %d\n", IsWindowVisible(hConsole));
                PYI_WARNING("LOADER: 3. ShowWindow updated: %d\n", succeeded);
            }
}
```

I was testing the result of the execution of `ShowWindow()` and `IsWindowVisible()`.
It was kind of random, some times worked (hide was ok) and some times not (hide failed),  but I did not try to debug "microsoft terminal" or anything further (not even sure how 😄 ).

Several times `IsWindowVisible()` returned 0 (unsuccessful) instead of 1 (successful).
Several times `ShowWindow()` returned 0 (unsuccessful) instead of 1 (successful).
I even tried to execute `IsWindowVisible()` and `ShowWindow()` 2-3 times right after each other.

But I had few times the correct behavior when wt.exe was hidden as expected due to `hide-early`.

For example, second execution worked:
```
[880] LOADER: 1. IsWindowVisible: 1
[880] LOADER: 1. ShowWindow updated: 0
[880] LOADER: 2. IsWindowVisible: 1
[880] LOADER: 2. ShowWindow updated: 1
```

For example, third execution still failed:
```
[15972] LOADER: 1. IsWindowVisible: 0
[15972] LOADER: 1. ShowWindow updated: 0
[15972] LOADER: 2. IsWindowVisible: 0
[15972] LOADER: 2. ShowWindow updated: 0
[15972] LOADER: 3. IsWindowVisible: 0
[15972] LOADER: 3. ShowWindow updated: 0
```

Any idea how to proceed? I mean this does not seem to be a pyinstaller issue to me but the perception of using pyinstaller is misleading since it seems the problem is with `hide_console` to average users.

**Comment by bwoodsend** [comment]
What do you expect us to do? Either we sit and wait until https://github.com/microsoft/terminal/issues/12464 does something or we kill the feature.

**Comment by bwoodsend** [comment]
I suppose the bootloader could print some warnings if ShowWindow() fails?

**Comment by rtommy** [comment]
> What do you expect us to do? Either we sit and wait until [microsoft/terminal#12464](https://github.com/microsoft/terminal/issues/12464) does something or we kill the feature.

I would not kill the feature as of yet, perhaps update `Automatic hiding and minimization of console window under Windows` section instead?
[https://github.com/pyinstaller/pyinstaller/blob/develop/doc/feature-notes.rst#automatic-hiding-and-minimization-of-console-window-under-windows](url)

I cannot reproduce the fault the way it's explained in that terminal ticket.

I have to use pyinstaller bootloader for that.

**Comment by rtommy** [comment]
> I suppose the bootloader could print some warnings if ShowWindow() fails?

Perhaps a WARNING message would be wise, indeed.

**Comment by rtommy** [comment]
No matter what `Default terminal application` is set for, Run: `powershell -WindowStyle Hidden -Command Sleep 5` always hides the window for me (it is clearly faster with `conhost` by the way). This way I am unable to reproduce the fault, it seems the `-WindowStyle Hidden` is correctly executed by `wt.exe` and `conhost.exe`?

**Comment by rokm** [comment]
I suppose we should add a note to docs that this is known not to work with Windows Terminal.

I don't see much point in the warning message - if we fail to hide/minimize the console, the failure is self-evident, and it is also non-actionable. So a warning would not do any good.

With `conhost.exe`, the obtained window handle is actually a true window handle, and thus `ShowWindow` works with it. 
With Windows Terminal, as far as I understand, the window handle is emulated, and some operations on it do not work (while others should nominally work, but they do not, or they work sporadically, likely due to some race condition). 

But I think Windows Terminal has conceptual issues with console window hiding/minimization, due to its tabbed interface. I.e., if a Windows Terminal instance is already opened and has some tabs open, you clearly wouldn't want an application to hide/minimize the whole window - perhaps only its own tab. But then if all other tabs are closed while application with hidden console is still running, what is supposed to happen with the terminal's (technically empty) window? Conversely, if an application is the first to open an actual Windows Terminal instance, and it requests to hide/minimize console window, what is supposed to happen? Hide/minimize the window, or just tab? But if this was the only tab, what do you do with the (technically empty) window? And what happens if user tries to open another terminal after the first, hidden/minimized, instance? There seem to be an awful lot of complications and corner cases, so I do not expect this to be resolved any time soon...

If you are hiding/minimizing console because you want an application that has console when launched from command prompt and no console when launched otherwise, I think the only reasonable approach right now is to create a shortcut for this second type of launch, where the application's executable is explicitly launched through `cmd.exe`. It would be nice if Microsoft allowed applications to specify whether they want to use `cmd.exe` or new Terminal or let Windows decide; for example, via option in the manifest. This way, the "Let Windows Decide" option in Terminal settings would actually be useful (as far as I know, that setting always launches Windows Terminal).

**Comment by rokm** [comment]
Also, according to https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow#return-value, the return value of `ShowWindow` does not indicate success/failure, but rather the previous state of the window.

**Comment by rokm** [comment]
Hmm, it also seems that sporadic success at hiding (actually, minimizing) the console window is indeed due to a race condition. When we issue ShowWindow() command, the window might not be yet considered visible, and so the request to hide/minimize it seems to be ignored.

Waiting for window to "become visible" seems to improve the behavior on my test Win11 VM:

```python
static void pyi_win32_adjust_console(int show_cmd)
{
    HWND hConsole = GetConsoleWindow();
    if (hConsole != NULL) {
        DWORD dwProcessId = GetCurrentProcessId();
        DWORD dwConsoleProcessId;

        if (GetWindowThreadProcessId(hConsole, &dwConsoleProcessId) == 0) {
            return; /* Window handle is invalid */
        }

        if (dwProcessId == dwConsoleProcessId) {
            while (!IsWindowVisible(hConsole)) {
                printf("Window not yet visible!\n");
                Sleep(100);
            }
            printf("HIDING WITH CMD: %d\n", show_cmd);
            BOOL ret = ShowWindow(hConsole, show_cmd);
            printf("RET: %d\n", ret);
            printf("IS VISIBLE: %d\n", IsWindowVisible(hConsole));
        }
    }
}
```

**Comment by rtommy** [comment]
> Also, according to https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow#return-value, the return value of `ShowWindow` does not indicate success/failure, but rather the previous state of the window.

That is true, I found the same when I was testing, I forgot to mention this.

**Comment by rtommy** [comment]
> Hmm, it also seems that sporadic success at hiding (actually, minimizing) the console window is indeed due to a race condition. When we issue ShowWindow() command, the window might not be yet considered visible, and so the request to hide/minimize it seems to be ignored.
> 
> Waiting for window to "become visible" seems to improve the behavior on my test Win11 VM:
> 
> ```python
> static void pyi_win32_adjust_console(int show_cmd)
> {
>     HWND hConsole = GetConsoleWindow();
>     if (hConsole != NULL) {
>         DWORD dwProcessId = GetCurrentProcessId();
>         DWORD dwConsoleProcessId;
> 
>         if (GetWindowThreadProcessId(hConsole, &dwConsoleProcessId) == 0) {
>             return; /* Window handle is invalid */
>         }
> 
>         if (dwProcessId == dwConsoleProcessId) {
>             while (!IsWindowVisible(hConsole)) {
>                 printf("Window not yet visible!\n");
>                 Sleep(100);
>             }
>             printf("HIDING WITH CMD: %d\n", show_cmd);
>             BOOL ret = ShowWindow(hConsole, show_cmd);
>             printf("RET: %d\n", ret);
>             printf("IS VISIBLE: %d\n", IsWindowVisible(hConsole));
>         }
>     }
> }
> ```

I agree, this must be a race condition issue. But I guess having a sleep() in the committed code is also not advisable, right?

**Comment by rtommy** [comment]
> I suppose we should add a note to docs that this is known not to work with Windows Terminal.
> 
> I don't see much point in the warning message - if we fail to hide/minimize the console, the failure is self-evident, and it is also non-actionable. So a warning would not do any good.
> 
> With `conhost.exe`, the obtained window handle is actually a true window handle, and thus `ShowWindow` works with it. With Windows Terminal, as far as I understand, the window handle is emulated, and some operations on it do not work (while others should nominally work, but they do not, or they work sporadically, likely due to some race condition).
> 
> But I think Windows Terminal has conceptual issues with console window hiding/minimization, due to its tabbed interface. I.e., if a Windows Terminal instance is already opened and has some tabs open, you clearly wouldn't want an application to hide/minimize the whole window - perhaps only its own tab. But then if all other tabs are closed while application with hidden console is still running, what is supposed to happen with the terminal's (technically empty) window? Conversely, if an application is the first to open an actual Windows Terminal instance, and it requests to hide/minimize console window, what is supposed to happen? Hide/minimize the window, or just tab? But if this was the only tab, what do you do with the (technically empty) window? And what happens if user tries to open another terminal after the first, hidden/minimized, instance? There seem to be an awful lot of complications and corner cases, so I do not expect this to be resolved any time soon...
> 
> If you are hiding/minimizing console because you want an application that has console when launched from command prompt and no console when launched otherwise, I think the only reasonable approach right now is to create a shortcut for this second type of launch, where the application's executable is explicitly launched through `cmd.exe`. It would be nice if Microsoft allowed applications to specify whether they want to use `cmd.exe` or new Terminal or let Windows decide; for example, via option in the manifest. This way, the "Let Windows Decide" option in Terminal settings would actually be useful (as far as I know, that setting always launches Windows Terminal).



So what I understand is that we have an option to select a Terminal Application: the legacy Console Host (`conhost.exe`) or the new  "shiny" Windows Terminal (`wt.exe`). The command prompt (`cmd.exe`) is actually a child process under the terminal application. So from Windows perspective, the main window application is not the command prompt (`cmd.exe`) but the terminal application itself. This means that the hide/minimize options are only valid for the Windows application and not the command prompt within. So it should not matter how many tabs we have within `wt.exe`, hide/minimize should work for the whole window, which actually worked for you too once you added sleep() to overcome of the race condition (bootloader basically opens a new terminal completely so there shall be one tab there for the command prompt). This is a same concept as with any other application with tabs such as Notepad++. You don't hide/minimize tabs within, you do it for the whole Notepad++ window.

I had the same thought why we don't have any API or a C function to control what Terminal application I want to use, what's the point of having "Let Windows decide" then? I was trying to find a solution for this but the only thing I found was to edit registry which is not really viable from the bootloader. I assume the windows/terminal code shall eventually provide (expose) a function for this....


Adding a note to the documentation makes sense, it would have helped me too to avoid my confusion. 😄

**Comment by rokm** [comment]
> I agree, this must be a race condition issue. But I guess having a sleep() in the committed code is also not advisable, right?

I'm quite fine with having a loop that performs five attempts with 100 ms delay; worst-case, we end up introducing a half-a-second delay (and only for applications that have opted in for this feature).

> So it should not matter how many tabs we have within wt.exe, hide/minimize should work for the whole window, which actually worked for you too once you added sleep() to overcome of the race condition (bootloader basically opens a new terminal completely so there shall be one tab there for the command prompt). This is a same concept as with any other application with tabs such as Notepad++. You don't hide/minimize tabs within, you do it for the whole Notepad++ window.

Sure, but is that what user expects/wants? You can configure Windows Terminal to open new tabs instead of new windows (`New Instance Behavior` setting, which can be either `Create a new window` (default), `Attached to the most recently used window` or `Attached to the most recently used window on this desktop`). In that case, if I already have a window with couple of tabs opened and I run application that tries to hide/minimize console, it will end up minimizing that window (I suppose this is one of the reasons why SW_HIDE also maps to minimize with Windows Terminal).

But I guess this is just another caveat that we will list in the note at the start of corresponding documentation section.

**Comment by rtommy** [comment]
You are absolutely right, and I clearly see your point. Perhaps for now just improve the documentation and mention about the Windows Terminal issues/limitations which prevents the hide_console works as expected and it is beyond pyinstaller obviously.
I am not sure adding that loop with max 5x100msec is the way forward but technically, it works.... could it be possible to "discuss" with the responsible developer team (if that actually exists)? 😄
