### ISSUE TITLE
Suggested solutions not working for: OSError: could not get source code

### ISSUE THREAD

**Issue by ashutoshmishra1014** [pyinstaller/pyinstaller#8594]
I have been following the instructions for packing with pyinstaller as mentioned here:
https://pyarmor.readthedocs.io/en/latest/topic/repack.html

### Description of the issue
OSError: could not get source code

### Context information (for bug reports)
Output of pyinstaller --version: 6.7.0
Version of Python: 3.8.16
Output of pyarmor --version: 8.5.7
Platform: Ubuntu 22.04
How you installed Python: conda
Did you also try this on another platform? Does it work there?: I haven't tried this on Windows yet, but I suspect it is probably also affected.

### A minimal example program which shows the error
My application is based on the below project:
https://github.com/nerfstudio-project/nerfstudio

which has as one of the dependencies on the the below package:
tyro
tyro is a tool for generating command-line interfaces and configuration objects in Python.

```
pyarmor gen -O dist2 -r nerfstudio/train.py nerfstudio/
python dist2/train.py
pyi-makespec --onefile nerfstudio/train.py
pyinstaller train.spec
dist/train
```

My spec file looks like this:
```
# # -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata, collect_all, is_module_satisfies
hiddenimports = []
datas = []
binaries = []
datas += copy_metadata('tqdm')
datas += copy_metadata('tyro')

# some other copy_metadata
datas += collect_data_files('wandb', include_py_files=True, includes=['**/vendor/**/*.py'])
datas += collect_data_files('tyro', include_py_files=True, includes=['**/*.py'])

# These are imports from vendored stuff in wandb
hiddenimports += collect_submodules('pathtools')
hiddenimports += collect_submodules('tinycudann_bindings')


a = Analysis(
    ['nerfstudio/train.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    module_collection_mode={
        'tyro': 'pyz+py',
    },
)
pyz = PYZ(a.pure)
....
```

### Stacktrace / full error message
I have already tried to include all the tyro python files by different ways (copy_metadata, collect_data_files & module_collection_mode) but yet when running `dist/train`, I get the below error:
```
   Traceback (most recent call last):
  File "tyro/_docstrings.py", line 128, in get_class_tokenization_with_field
  File "tyro/_unsafe_cache.py", line 33, in wrapped_f
  File "tyro/_docstrings.py", line 47, in make
  File "inspect.py", line 997, in getsource
  File "inspect.py", line 979, in getsourcelines
  File "inspect.py", line 798, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nerfstudio/train.py", line 270, in <module>
    entrypoint()
  File "nerfstudio/train.py", line 262, in entrypoint
    tyro.cli(
  File "tyro/_cli.py", line 187, in cli
  File "tyro/_cli.py", line 378, in _cli_impl
  File "tyro/_parsers.py", line 82, in from_callable_or_type
  File "tyro/_fields.py", line 281, in field_list_from_callable
  File "tyro/_fields.py", line 423, in _try_field_list_from_callable
  File "tyro/_fields.py", line 591, in _field_list_from_dataclass
  File "tyro/_unsafe_cache.py", line 33, in wrapped_f
  File "tyro/_docstrings.py", line 171, in get_field_docstring
  File "tyro/_unsafe_cache.py", line 33, in wrapped_f
  File "tyro/_docstrings.py", line 130, in get_class_tokenization_with_field
AssertionError
[1176521] Failed to execute script 'train' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
*could not get source code* means that you need to collect the original `.py` source code. See #8013

I'd be surprised though if this works with pyarmor since it'll want to render the source code unreadable. But that's between you and pyarmor -- we don't want to be involved in code obfuscation.

**Comment by ashutoshmishra1014** [comment]
@bwoodsend Could you please reopen the issue?

As you might have noticed, I tried the solution suggested in https://github.com/pyinstaller/pyinstaller/issues/8013, and it did not work.

I also tried without using the pyarmor and yet it does not work.
I tried below:
```
pyinstaller nerfstudio/train.py 
pyinstaller train.spec (after making the changes as suggested in https://github.com/pyinstaller/pyinstaller/issues/8013)
dist/train/train
```

Here is my current train.spec file:
```
# # -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata, collect_all, is_module_satisfies
hiddenimports = []
datas = []
binaries = []
datas += copy_metadata('tqdm')
datas += copy_metadata('tyro')

# some other copy_metadata
datas += collect_data_files('wandb', include_py_files=True, includes=['**/vendor/**/*.py'])
datas += collect_data_files('tyro', include_py_files=True, includes=['**/*.py'])

# These are imports from vendored stuff in wandb
hiddenimports += collect_submodules('pathtools')
hiddenimports += collect_submodules('tinycudann_bindings')


a = Analysis(
    ['nerfstudio/train.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    module_collection_mode={
        'tyro': 'pyz+py',
    },
)
pyz = PYZ(a.pure)
....
```
Stacktrace/Error:
```
Traceback (most recent call last):
  File "tyro/_docstrings.py", line 128, in get_class_tokenization_with_field
  File "tyro/_unsafe_cache.py", line 33, in wrapped_f
  File "tyro/_docstrings.py", line 47, in make
  File "inspect.py", line 997, in getsource
  File "inspect.py", line 979, in getsourcelines
  File "inspect.py", line 798, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nerfstudio/train.py", line 270, in <module>
    entrypoint()
  File "nerfstudio/train.py", line 262, in entrypoint
    tyro.cli(
  File "tyro/_cli.py", line 187, in cli
  File "tyro/_cli.py", line 378, in _cli_impl
  File "tyro/_parsers.py", line 82, in from_callable_or_type
  File "tyro/_fields.py", line 281, in field_list_from_callable
  File "tyro/_fields.py", line 423, in _try_field_list_from_callable
  File "tyro/_fields.py", line 591, in _field_list_from_dataclass
  File "tyro/_unsafe_cache.py", line 33, in wrapped_f
  File "tyro/_docstrings.py", line 171, in get_field_docstring
  File "tyro/_unsafe_cache.py", line 33, in wrapped_f
  File "tyro/_docstrings.py", line 130, in get_class_tokenization_with_field
AssertionError
[1207268] Failed to execute script 'train' due to unhandled exception!
```

**Comment by rokm** [comment]
You'll need to figure out what package's source code actually needs to be collected - perhaps `nerfstudio` instead of `tyro`, or both...

**Comment by rokm** [comment]
Or perhaps `tyro` requires source code of your entry-point script.

**Comment by rokm** [comment]
> Or perhaps `tyro` requires source code of your entry-point script.

I think this is the case; this [`tyro` example](https://github.com/brentyi/tyro/blob/main/examples/03_config_systems/01_base_configs.py) seems to raise the same kind of error. 

And to make it work, `tyro._cli` needs to be collected as source (i.e., `'tyro._cli': 'pyz+py',` although `'tyro': 'pyz+py',` should also do the trick). And the entry-point script needs to be collected as a data file (since entry points are treated differently from modules, this cannot be done via `module_collection_mode` setting).

So in your case, you probably need to add `('nerfstudio/train.py', '.')` entry to `datas`. 

I imagine that requiring source code to be available for `tyro`'s introspection inherently makes the code incompatible with `pyarmor`; but that has nothing to do PyInstaller.

**Comment by ashutoshmishra1014** [comment]
@rokm I used all your suggestions above and the error still remains the same (not using pyarmor obfuscation anymore just plain pyinstaller).

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata, collect_all, is_module_satisfies
hiddenimports = []
datas = []
binaries = []
datas += copy_metadata('tqdm')
datas += copy_metadata('tyro')
datas += copy_metadata('nerfstudio')

# some other copy_metadata
datas += collect_data_files('wandb', include_py_files=True, includes=['**/vendor/**/*.py'])
datas += collect_data_files('tyro', include_py_files=True, includes=['**/*.py'])
datas += collect_data_files('nerfstudio', include_py_files=True, includes=['**/*.py'])
datas += [('nerfstudio/train.py', '.')]


# These are imports from vendored stuff in wandb
hiddenimports += collect_submodules('pathtools')
hiddenimports += collect_submodules('tinycudann_bindings')
hiddenimports += collect_submodules('nerfstudio')


a = Analysis(
    ['nerfstudio/train.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    module_collection_mode={
        'tyro._cli': 'pyz+py',
        'nerfstudio': 'pyz+py'
    },
)
pyz = PYZ(a.pure)
....
```

**Comment by ashutoshmishra1014** [comment]
I also tried adding each of the modules individually, the ones that `tyro/_docstrings.py", line 130, in get_class_tokenization_with_field` is trying to inspect and get the source. It still doesn't work.
```
    module_collection_mode={
        'tyro._cli': 'pyz+py',
        'types': 'pyz+py',
        'nerfstudio.engine.trainer': 'pyz+py',
        'nerfstudio.configs.experiment_config': 'pyz+py',
        'nerfstudio.configs.external_methods': 'pyz+py',
        'nerfstudio.configs.base_config': 'pyz+py',
        'nerfstudio.pipelines.base_pipeline': 'pyz+py',
        'nerfstudio.data.datamanagers.base_datamanager': 'pyz+py',
        'nerfstudio.cameras.camera_optimizers': 'pyz+py',
        'nerfstudio.engine.optimizers': 'pyz+py',
        'nerfstudio.engine.schedulers': 'pyz+py',
        'nerfstudio.data.dataparsers.nerfstudio_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.minimal_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.arkitscenes_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.blender_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.instant_ngp_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.nuscenes_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.dnerf_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.phototourism_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.dycheck_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.scannet_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.sdfstudio_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.nerfosr_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.sitcoms3d_dataparser': 'pyz+py',
        'nerfstudio.data.dataparsers.colmap_dataparser': 'pyz+py',
        'nerfstudio.data.pixel_samplers': 'pyz+py',
        'nerfstudio.models.base_model': 'pyz+py',
        'nerfstudio.data.pixel_samplers': 'pyz+py',
        'nerfstudio.models.depth_nerfacto': 'pyz+py',
        'nerfstudio.models.nerfacto': 'pyz+py',
        'nerfstudio.models.vanilla_nerf': 'pyz+py',
        'nerfstudio.data.datamanagers.random_cameras_datamanager': 'pyz+py',
        'nerfstudio.models.generfacto': 'pyz+py',
        'nerfstudio.pipelines.dynamic_batch': 'pyz+py',
        'nerfstudio.models.instant_ngp': 'pyz+py',
        'nerfstudio.models.semantic_nerfw': 'pyz+py',
        'nerfstudio.models.tensorf': 'pyz+py',
        'nerfstudio.configs.external_methods': 'pyz+py',
    },
)
pyz = PYZ(a.pure)
....
```

**Comment by rokm** [comment]
Yeah, I was going to suggest that you instrument your local copy of `tyro`, so you can see what modules it is trying to retrieve the source for.

I.e., add a line
```python
        print("---> GETSOURCE:", clz)
``` 
before this line:
https://github.com/brentyi/tyro/blob/720be8b5e63b7a57c7044afe32bb6776a020d9ec/src/tyro/_docstrings.py#L47 (might not be exact line, depending on your version of `tyro`)

It should then print the names of modules (actually classes within modules).

Have you determined the above list of modules in this way?

**Comment by rokm** [comment]
Also, `'nerfstudio': 'pyz+py'` should collect all of them. But you might need to do a `hiddenimports += collect_submodules('nerfstudio')` as well. 

All in all, it would be easier if you temporarily switched from onefile build to onedir, so you can inspect its contents. Or inspect the contents of onefile build using `pyi-archive_viewer`. But with onedir, you could also just manually copy the files until it starts working...

**Comment by ashutoshmishra1014** [comment]
> Yeah, I was going to suggest that you instrument your local copy of `tyro`, so you can see what modules it is trying to retrieve the source for.
> 
> I.e., add a line
> 
> ```python
>         print("---> GETSOURCE:", clz)
> ```
> 
> before this line: https://github.com/brentyi/tyro/blob/720be8b5e63b7a57c7044afe32bb6776a020d9ec/src/tyro/_docstrings.py#L47 (might not be exact line, depending on your version of `tyro`)
> 
> It should then print the names of modules (actually classes within modules).
> 
> Have you determined the above list of modules in this way?

Yes, I did exactly what you suggested.

**Comment by ashutoshmishra1014** [comment]
> Also, `'nerfstudio': 'pyz+py'` should collect all of them. But you might need to do a `hiddenimports += collect_submodules('nerfstudio')` as well.
> 
> All in all, it would be easier if you temporarily switched from onefile build to onedir, so you can inspect its contents. Or inspect the contents of onefile build using `pyi-archive_viewer`. But with onedir, you could also just manually copy the files until it starts working...

Let me try this, will get back to you soon.

**Comment by rokm** [comment]
> > Yeah, I was going to suggest that you instrument your local copy of `tyro`, so you can see what modules it is trying to retrieve the source for.
> > I.e., add a line
> > ```python
> >         print("---> GETSOURCE:", clz)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > before this line: https://github.com/brentyi/tyro/blob/720be8b5e63b7a57c7044afe32bb6776a020d9ec/src/tyro/_docstrings.py#L47 (might not be exact line, depending on your version of `tyro`)
> > It should then print the names of modules (actually classes within modules).
> > Have you determined the above list of modules in this way?
> 
> Yes, I did exactly what you suggested.

Which module/class did it fail with, then?

**Comment by ashutoshmishra1014** [comment]
I think I misunderstood you. I fetched the list of all the modules by running the original file `nerfstudio/train.py` so that tyro CLI gets triggered and I could get all the modules that it gathers for inspections. Then in the next step, I add those modules in the `module_collection_mode' while building with pyinstaller.

Also, when I do `pyinstaller train.spec` (onefile setting) and then try to edit the `_docstrings.py` inside `dist/train/_internal/tyro` for `print("---> GETSOURCE:", clz)` and then run `dist/train/train`, somehow my change in the file does not work as if it is pointing to a different file. Am I understanding things wrong here? I believed the libs inside `dist/train/_internal` should be the ones being used by my executable `dist/train/train`.

**Comment by rokm** [comment]
> I think I misunderstood you. I fetched the list of all the modules by running the original file `nerfstudio/train.py` so that tyro CLI gets triggered and I could get all the modules that it gathers for inspections. Then in the next step, I add those modules in the `module_collection_mode' while building with pyinstaller.
> 
> Also, when I do `pyinstaller train.spec` (onefile setting) and then try to edit the `_docstrings.py` inside `dist/train/_internal/tyro` for `print("---> GETSOURCE:", clz)` and then run `dist/train/train`, somehow my change in the file does not work as if it is pointing to a different file. Am I understanding things wrong here? I believed the libs inside `dist/train/_internal` should be the ones being used by my executable `dist/train/train`.

In typical scenarios, the change needs to be done before the modules are collected. 

Those .py files that are collected into  `dist/train/_internal/tyro` are used only for source, but what is executed are .pyc compiled modules in the PYZ archive (so packages that need sources are not ideal for PyInstaller, because we usually need to collect both .pyc compiled module and source .py file, and the two are essentially decoupled). If you set collection mode for `tyro` (the whole package) to `py` (instead of `pyz+py`), then only .py files are collected, and also executed. But it would be easier to instrument the `tyro` copy in your environment, and then rebuild the application so that it collects the modified/instrumented version of `tyro`.

**Comment by ashutoshmishra1014** [comment]
Thank you so much for your explanation.BTW, the missing module appeared as `---> GETSOURCE: <class 'types.dummy'>`

**Comment by rokm** [comment]
> Thank you so much for your explanation.BTW, the missing module appeared as `---> GETSOURCE: <class 'types.dummy'>`

Hmm, that should be solved by ensuring `types` is collected as source. But I think you already have `'types': 'pyz+py'` - do you see `types.py` in `dist/train/train/_internal`?

**Comment by ashutoshmishra1014** [comment]
No, there is no `types.py` in there. May be `module_collection_mode` does not work for python base libraries like `types`.
In order to force copying the source: I did this instead:
```
datas += [('<env-path>/lib/python3.8/types.py', '.')]
```
Now I can see `types.py` inside `dist/train/_internal` but still the same error.

However I found something interesting, inside the `base_library.zip` file I can find the compiled filed i.e `types.pyc'.

Is there a way to copy the source for the python base packages inside the `base_library.zip`. I do not know but may be that is the place where the source .py for `types` is to be placed.

**Comment by rokm** [comment]
Yeah, if the module is in `base_library.zip`, then source-code is handled by python's built-in importer, and that won't work with .py files that are collected as data files or via module collection mode.

In this case, your only recourse is to either manually add `types.py` into `base_library.zip`, or to monkey-patch `PyInstaller.depend.utils.create_py3_base_library` at the top of .spec file with custom implementation that includes that .py file in the archive.

**Comment by rokm** [comment]
But this means that this would also fail with python.org embeddable python builds, where all stdlib modules are provided only as byte-compiled .pyc, so whoever is responsible for trying to introspect stdlib modules via source code (`tyro` or `nerfstudio`) should deal with this.

**Comment by ashutoshmishra1014** [comment]
I was able to solve these issues by manually adding the missing core files (types.py, enum.py) into the base_library.zip.
However, it fails to work with the numpy module. I tried the options below:
1. Option1
`hiddenimports += collect_submodules('numpy')`
Error:
```
/home/mha/conda/DSAI/pyarmor/lib/python3.8/site-packages/PyInstaller/utils/hooks/__init__.py:653: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(name)
3155 INFO: Module search paths (PYTHONPATH):
['<conda env path>/python38.zip',
 '<conda env path>/lib/python3.8',
 '<conda env path>/lib/python3.8/lib-dynload',
 '<conda env path>/lib/python3.8/site-packages',
 '__editable__.nerfstudio-1.0.1.finder.__path_hook__',
 '<current folder path>']
Error: Invalid hiddenimport 'numpy._pyinstaller.hook-numpy'. Hidden imports should be importable module names – not file paths. i.e. use --hiddenimport=foo.bar instead of --hiddenimport=.../site-packages/foo/bar.py
```
2. Option2
```
    module_collection_mode={
        'nerfstudio': 'pyz+py',
        'numpy': 'pyz+py'
    },
```
Can not find numpy entry in the list from `pyi-archive_viewer`
3. Option3
Manually copying the numpy folder from the site-packages in base_library.zip file
Error: something related to missing .so files

**Comment by rokm** [comment]
Option 2 is the only reasonable one here, and it should work (i.e., if I set `module_collection_mode` for `numpy` to `pyz+py` for a `numpy`-enabled program, I can see `numpy` .py files collected into the frozen application, onedir or onefile).
